netty/netty-tcnative

- openssl-dynamic/src/main/c/ssl.c
Motivation:
We allow a user to specify which openssl engine should be used. To make it easier and allow the user to just specify OPENSSL_ENGINES=/path/to/the/engines we should call ENGINE_load_builtin_engines() before we try to lookup the engine per id.
Modifications:
Call ENGINE_load_builtin_engines() before trying to lookup the engine and also ensure we call ENGINE_cleanup() when needed.
Result:
Easier to use a custom openssl engine.
> Call ENGINE_load_builtin_engines() when a custom engine was specified

- openssl-dynamic/src/main/c/sslcontext.c
Motivation:
We missed to correctly init all fields of tcn_ssl_task_t and so may run into problem if OPENSSL_malloc(...) does not memset when allocating.
Modifications:
- Add two helper functions, one to init tcn_ssl_task_t and one to free tcn_ssl_task_t pointers to ensure we never fail to init all fields again.
- Use these functions
Result:
Always correctly init all fields of tcn_ssl_task_t.
> correct init all fields of tcn_ssl_task_t in all cases.

- openssl-dynamic/src/main/c/sslcontext.c
Motivation:
When realloc(...) fails and so return NULL we need to ensure we free the original (source) pointer to not leak memory.
Modifications:
Correctly call free(...) when realloc(...) fails.
Result:
No more memory leak when realloc fails.
> Correctly free source pointer when realloc(...) fails

- docker/docker-compose.centos-6.18.yaml
- docker/docker-compose.debian-7.18.yaml
Motivation:
There is a new java8 release
Modifications:
Update to latest release
Result:
Use latest java8 release on CI
> Update Java version

- .github/workflows/ci-build.yml
- .github/workflows/ci-deploy.yml
- docker/Dockerfile.cross_compile_aarch64
- docker/Dockerfile.debian
- docker/docker-compose.arch.yaml
- docker/docker-compose.centos-7.yaml
- docker/docker-compose.debian-7.18.yaml
- docker/docker-compose.debian.yaml
- docker/docker-compose.opensuse.yaml
Motivation:
We also need to compile for debian and also for aarch64
Modifications:
- Add jobs for cross compiling and debian
- Adjust docker file to cache deps
Result:
Also handle os linux arch / versions that we support
> Add jobs for debian and cross compiling

- .github/workflows/ci-deploy.yml
- .github/workflows/ci-pr.yml
Motivation:
We should better use seperate workflows for PR and normal builds
Modifications:
- Split workflows
Result:
Cleanup
> Split pr and normal build (#10884)

- .github/scripts/check_build_result.sh
- .github/workflows/ci-build.yml
- .github/workflows/ci-pr.yml
Motivation:
We should ensure we detect any test failure by inspecting the build output
Modifications:
Add script which checks the build output
Result:
Fail build on test failure
> Use script to detect test failures

- .github/workflows/ci-build.yml
- .github/workflows/ci-deploy.yml
- .github/workflows/ci-pr.yml
Motivation:
We do also release for windows, let's use a job to build via github action for windows as well
Modifications:
Add the job for PR and normal builds
Result:
Workflow jobs for windows
> Add build for windows

- boringssl-static/pom.xml
Motivation:
We don't need decrepit at all and so should not link it
Modifications:
Remove decrepit linking
Result:
Only link what we really need
> Don't link decrepit

- .github/scripts/merge_local_staging.sh
- .github/scripts/release_checkout_tag.sh
- .github/scripts/release_rollback.ps1
- .github/scripts/release_rollback.sh
- .github/workflows/ci-release.yml
- docker/docker-compose.centos-6.18.yaml
- docker/docker-compose.centos-6.yaml
- docker/docker-compose.centos-7.yaml
- docker/docker-compose.debian-7.18.yaml
- docker/docker-compose.debian.yaml
- pom.xml
Motivation:
Doing releases manually is error-prone, it would be better if we could do it via a workflow
Modification:
- Add workflow to cut releases
- Add related scripts
Result:
Be able to easily cut a release via a workflow
> Add workflow to cut releases

- scripts/finish_release.sh
Motivation:
After the release workflow was done we need to run some extra commands.
Modifications:
Add a script to run
Result:
Easier to do a release
> Add script to finish release

- pom.xml
Motivation:
A new version of netty-build was released
Modifications:
Update to latest version
Result:
Use latest netty-build
> Update to latest netty-build

- docker/docker-compose.centos-7.yaml
Motivation:
We did forget to remove some popd calls before which did cause the build to fail
Modifications:
Remove popd
Result:
Cross compile works again
> Fix docker-compose file for cross compiling

- docker/docker-compose.centos-6.18.yaml
- docker/docker-compose.debian-7.18.yaml
Motivation:
There are new java version
Modifications:
Update all java versions to latest patch release
Result:
Use latest java versions on the CI
> Update java versions

- pom.xml
Motivation:
We need to have a developers section in the pom.xml as otherwise the validation will fail during the release
Modifications:
Add missing sections
Result:
No more failure during validation
> Add missing sections to pom.xml

- pom.xml
Related:
- https://github.com/netty/netty-tcnative/pull/420
- https://github.com/netty/netty-jni-util/pull/13
- https://github.com/netty/netty/pull/12358
> Update `netty-jni-util` from `0.0.5.Final` to `0.0.6.Final`

- docker/docker-compose.centos-6.18.yaml
- docker/docker-compose.debian-7.18.yaml
Motivation:
There was a new java 8 release
Modifications:
Update to 8.0.332-zulu
Result:
Build with latest java8 release
> Update to 8.0.332-zulu

- .github/workflows/ci-deploy.yml
- .github/workflows/ci-release.yml
- .github/workflows/codeql-analysis.yml
Motivation:
ubuntu-18.04 is deprecated. Let's just use ubuntu-latest
Modifications:
Use ubuntu-latest in workflows
Result:
Cleanup
> Use ubuntu-latest in workflows

- docker/docker-compose.centos-6.18.yaml
- docker/docker-compose.debian-7.18.yaml
Motivation:
We dont use the latest release atm
Modifications:
Update to 8.0.352
Result:
Use latest release on the CI.
> Update to latest java8 release

- .mvn/wrapper/maven-wrapper.properties
- docker/Dockerfile.centos6
- docker/Dockerfile.cross_compile_aarch64
- docker/Dockerfile.debian
Motivation:
Let's update to maven 3.8.7
Modifications:
Update to latest version
Result:
Use latest maven version
> Update to latest maven version

- .mvn/wrapper/maven-wrapper.properties
- docker/Dockerfile.centos6
- docker/Dockerfile.cross_compile_aarch64
- docker/Dockerfile.debian
- docker/docker-compose.centos-6.yaml
- docker/docker-compose.centos-7.yaml
- docker/docker-compose.debian.yaml
Motivation:
There was a new maven release we should use. Also just use sdkman to do so.
Modifications:
- Upgrade to maven 3.9.1
- Use sdkman
Result:
Use latest maven version and use sdkman
> Upgrade to latest maven version and use sdkman to install it

- openssl-dynamic/src/main/c/ssl.c
Motivation:
Let's remive the unused variable
Modifications:
Remove unused var
Result:
Cleanup
> Remove unused variable

- docker/Dockerfile.debian
Motivation:
Lets be consistent and just use curl
Modifications:
Replace wget with curl
Result:
Cleanup
> Replace wget usage with curl

- .github/workflows/codeql-analysis.yml
Fixes #778 (again).
This PR is a continuation of #779... I missed one of the workflows! 🤦‍♂️
> Add minimal permissions to codeql-analysis.yml

- docker/docker-compose.centos-6.18.yaml
- docker/docker-compose.debian-7.18.yaml
Motivation:
There are new releases of java.
Modifications:
Upgrade java versions to latest release
Result:
Use latest versions on the CI
> Upgrade java versions

- .github/workflows/ci-build.yml
- .github/workflows/ci-deploy.yml
- .github/workflows/ci-pr.yml
- .github/workflows/ci-release.yml
Motivation:
There were various updates to the github actions
Modifications:
Update github actions
Result:
Cleanup
> Update github actions

- .github/workflows/ci-release.yml
Motivation:
We should update the action to eliminate warnings during action run
Modifications:
Update action to use latest version
Result:
No more warnings
> Update action that uses deprecated node

- docker/docker-compose.centos-6.18.yaml
- docker/docker-compose.debian-7.18.yaml
Motivation:
We didnt use the latest java releases on the CI
Modifications:
Update java releases
Result:
Use latest java releases on the CI
> Upgrade java versions to latest patch release

- .github/workflows/ci-build.yml
- .github/workflows/ci-deploy.yml
- .github/workflows/ci-pr.yml
- .github/workflows/ci-release.yml
- .github/workflows/codeql-analysis.yml
Motivation:
We should keep our actions up to date.
Modifications:
Upgrade all github actions to latest releases
Result:
Housekeeping
> Update github actions to latest versions

- docker/docker-compose.centos-6.18.yaml
- docker/docker-compose.debian-7.18.yaml
Motivation:
There is an ew java8 release
Modifications:
Update to 8.0.402-zulu
Result:
Use latest release
> Update to java 8.0.402-zulu

- .github/workflows/ci-build.yml
- .github/workflows/ci-deploy.yml
- .github/workflows/ci-pr.yml
- .github/workflows/ci-release.yml
- docker/README.md
Motivation:
docker-compose is no more and you should use docker compose
Modifications:
Replace docker-compose with docker compose
Result:
Build works again
> Replace docker-compose with docker compose

- boringssl-static/pom.xml
- libressl-static/pom.xml
- openssl-dynamic/pom.xml
- openssl-static/pom.xml
Motivation:
We need to generate source for all artifacts that we publish as otherwise the release process will fail
Modifications:
Generate source jars when needed
Result:
Release process does not fail anymore
> Ensure we generate sources for all artifacts (#881)

- docker/Dockerfile.cross_compile_aarch64
- docker/docker-compose.centos-7.yaml
- pom.xml
Motivation:
A new apr version was released
Modifications:
Upgrade to 1.7.5
Result:
Use latest apr version
> Upgrade to apr 1.7.5

- boringssl-static/pom.xml
Motivation:
We didnt pass the correct flag to cmake
Modifications:
Pass correct flag
Result:
Correct build on windows
> Use -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded

- .github/workflows/ci-pr.yml
Motivation:
Let's also build on macOS on the CI
Modifications:
Add macos runner for aarch64 and x86_64
Result:
Ensure we can build on macOS
> Build on macOS
