src/main/c/ssl.c
Motivation:
For CONF_modules_unload, it looks like it should simply not be called for BoringSSL. It's intended to cleanup after calling OPENSSL_load_builtin_modules, which is not called for BoringSSL.
Modifications:
Modified ssl.c to not call CONF_modules_unload if BoringSSL
Result:
Addresses part of #65
=> Do not call CONF_modules_unload for BoringSSL

src/main/c/sslcontext.c
Motivation:
Generally trying to cleanup build errors/warnings.
Modifications:
Modified the setCertificateBio method to remove unused variable.
Result:
Fixes build error.
=> Removing unused variable in sslcontext.c

boringssl-static/pom.xml, libressl-static/pom.xml, openssl-static/pom.xml
Motivation:
Our current deploy process requires that we start on centos first. Since we only generate one boring-static jar for linux, this means that it will be overwritten when we get to debian. Debian has a higher glibc version, which will release a jar that ultimately won't work on old versions of centos.
Modifications:
Modified the boringssl module to only deploy if on centos.
Result:
Our deploy process works :)
=> Only deploy static jar on centos

openssl-dynamic/pom.xml
Motivation:
The new structure seems to have broken the addition of "-fedora" to the classifier for fedora-like systems.
Modifications:
Update the configuration to set both classifier and nativeJarFile when detecting fedora.
Result:
The dynamic lib should now have -fedora for fedora-like systems.
=> Dynamic lib needs -fedora classifier

openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/java/io/netty/internal/tcnative/SSL.java
See https://github.com/netty/netty/issues/6320 for the only user of this function, and the related discussion.
After this change, netty-tcnative will build on Debian sid/unstable, against openssl 1.1.
---
`SSL_set_state` has gone from openssl 1.1. Calling it is, and probably always has been, incorrect. It has only ever been used to drive an incorrect renegotiation algorithm. Doing renegotiation in this manner is potentially insecure. There have been at least two insecure renegotiation vulnerabilities in users of the OpenSSL library.
Renegotiation is not necessary for correct operation of the TLS protocol.
Remove the method, and its implementation.
Fixes: #263
Requires: https://github.com/netty/netty/issues/6320
=> Remove calls to SSL_set_state

pom.xml
Motivation:
We should use the latest openssl version in our builds.
Modifications:
Update to openssl 1.0.2n
Result:
Compile against latest openssl version
=> Update to openssl 1.0.2n

pom.xml
Motivation:
Use latest stable libressl version
Modifications:
Bump up version to 2.6.4
Result:
Building against latest libressl version
=> Update to libressl 2.6.4

openssl-dynamic/src/main/c/ssl.c
BoringSSL is going to make using the “zero length means call strlen” an
error for various reasons so this change will allow the code to continue
working with BoringSSL. Additionally, by passing a length, OpenSSL can
catch cases where there's an embedded NUL in the string. Lastly, it's
not clear that JNI guarantees that the result of GetStringUTFChars is
NUL terminated[1].
This change also makes an empty hostname an error. OpenSSL considers
setting an empty hostname to disable all checks, but that seems like a
surprising behaviour when this function already supports `null` to skip
hostname checking.
[1] https://docs.oracle.com/javase/6/docs/technotes/guides/jni/spec/functions.html#wp17265
=> Pass a string length to X509_VERIFY_PARAM_set1_host.

openssl-dynamic/src/main/c/ssl_private.h, pom.xml
Motivation:
Change the version of libressl to 2.7.3 for netty-tcnative-libressl-static and so ensure we can also compile with newer versions of libressl.
Modifications:
Slightly change the ifdef to only define OPENSSL_VERSION if not using libressl 2.7.x
Result:
Use latest libressl
=> Compile libressl-static against libressl 2.7.3

docker/Dockerfile.centos, docker/Dockerfile.debian, docker/README.md, docker/docker-compose.centos-6.18.yaml, docker/docker-compose.centos.yaml, docker/docker-compose.debian-7.18.yaml, docker/docker-compose.debian.yaml
Motivation:
We should just use docker-compose to allow easy building via docker for the linux distributions we support. This will allow us to enhance to use different java versions easily and we will be able to re-use these for the CI.
Modifications:
Replace old dockerfiles with new ones that are used via docker-compose.
Result:
Easily be able to build netty-tcnative for supported distributions.
=> Providing docker-compose files for centos6 / debian7

openssl-dynamic/src/main/c/jnilib.c
Motivation:
Some users may want to use netty-tcnative on Solaris. This is currently not possible as we try to use strndup on Solaris which doesn't exists.
Modifications:
Don't try to use strndup on solaris but just use our own impl (as we do for windoes as well).
Result:
Fixes https://github.com/netty/netty-tcnative/issues/349.
=> Don't try to use strndup on Solaris as it not exists.

pom.xml
Motivation:
We should use the latest version of openssl.
Modifications:
update from 1.0.2n to 1.0.2o
Result:
Use latest version of openssl.
=> Use openssl 1.0.2o for static artifact.

openssl-dynamic/src/main/c/sslcontext.c
Motivation:
There is a memory leak in the first certificate of the chain parsed in
cert_requested(). How to reproduce this is described in #353. It's
possible that this was introduced by 0572eabf06.
Modifications:
Remove the extra ref up on the first certificate of the chain.
Result:
Fixes https://github.com/netty/netty-tcnative/issues/353
=> Fix memory leak in cert_requested()

openssl-dynamic/src/main/c/ssl_private.h, openssl-dynamic/src/main/c/sslutils.c
Motivation:
This function isn't used, it is a leftover from the fix for #353.
Modifications:
Remove the unused function.
Result:
No more dead code.
=> Remove unused function tcn_X509_up_ref

pom.xml
Motivation:
We currently use openssl 1.0.2o when compiling openssl-static, but we should just switch to 1.1.0h for now as it replace a lot of locking with thread-local opertions.
Modifications:
Upgrade to openssl 1.1.0h.
Result:
More recent version of openssl used when compile openssl-static.
=> Update to openssl 1.1.0h when compiling openssl-static

pom.xml
Motivation:
We should use the latest libressl version for our libressl-static build.
Modifications:
Update from 2.7.3 to 2.7.4
Result:
Use latest libressl
=> Update to libressl 2.7.4 for libressl-static

boringssl-static/pom.xml
Motivation:
At the moment we completely strip the netty-tcnative-boringssl-static lib which makes it impossible to profile / debug the native code. We should limit the stripping to debug symbols to still be able to see at least the functions that are colled.
Modifications:
Use strip --strip-debug on linux.
Result:
Fixes https://github.com/netty/netty-tcnative/issues/359. The lib is only ca 100k bigger then before.
=> We should only strip debug symbols

openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/c/ssl_private.h, openssl-dynamic/src/main/c/sslcontext.c, openssl-dynamic/src/main/c/sslutils.c
Motivation:
We currently named some of our internal functions SSL_* which is kind of confusing and may even clash with functions provided by OpenSSL in the future. We should rename these to start with TCN or something like that.
Modifications:
Prefix all of these functions with tcn_
Result:
No more clashing possible. Fixes https://github.com/netty/netty-tcnative/issues/361 .
=> Rename internal functions so these start with tcn_

openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/c/sslcontext.c, openssl-dynamic/src/main/c/tcn.h
Motivation:
GetStringUTFChars(...) list JNI_FALSE as its argument in the docs, we should use it and not depend on the fact that 0 == JNI_FALSE.
Modifications:
Replace 0 by JNI_FALSE when using GetStringUTFChars.
Result:
Cleaner code.
=> Use JNI_FALSE when calling GetStringUTFChars(...) and not 0

openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/java/io/netty/internal/tcnative/SSL.java
Motivation:
We had some users that are interested to build their own netty-tcnative artifacts and use FIPS. We should allow to enable it.
Modifications:
Allow to change the fips mode if its compiled with support for it.
Result:
Possible to use netty-tcnative with FIPS.
=> Allow to set FIPS mode if compiled with FIPS support.

openssl-static/pom.xml, pom.xml
Openssl 1.1 build changed on windows: 
1. Remove call to ms/do_win64a.bat
2. Change names of resulting ssl lib files.
=> Fix Openssl build on windows

openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/java/io/netty/internal/tcnative/SSL.java
Motivation:
Its possible to plugin different behavior into OpenSSL by providing a custom OpenSSL engine. When doing so it's possible to load a private key from the engine directly.
Modifications:
Add new method which allows to load a private key from the OpenSSL engine directly and so can be used later on.
Result:
Be able to implement custom loading / store mechanism of private keys via a custom OpenSSL engine.
=> Allow to load a private key from the OpenSSL engine.

openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/c/ssl_private.h, openssl-dynamic/src/main/c/sslutils.c
Motivation:
We did not support DH with some versions of OpenSSL / BoringSSL / LibreSSL.
Modifications:
- Remove some ifdefs etc and adjust the code to work with all of the SSL flavors we support.
Result:
Fixes https://github.com/netty/netty/issues/8165.
=> Correctly support DH with all versions of OpenSSL / BoringSSL / LibreSSL

boringssl-static/pom.xml, libressl-static/pom.xml, openssl-static/pom.xml, pom.xml
Motivation:
At the moment we redownload and re-compile APR / *SSL when building our static compiled version of netty-tcnative even if it was compiled before and we did not request a "clean" during the build. We should better only do it when "clean" is explicit requested to speed up build times when working on changes.
Modifications:
Verify if we already compiled APR / *SSL and if so skip the step.
Result:
Be able to faster iterate and build
=> Skip re-download and re-compile of APR / *SSL when already done before.

openssl-static/pom.xml
Motivation:
We do not care about the openssl manpages so there is no need to install them during the build.
Modifications:
Use make install_sw which will skip manpage installation.
Result:
Faster build
=> Do not install man-pages during openssl-static build to speed up things.

openssl-dynamic/src/main/c/native_constants.c, openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/c/ssl_private.h, openssl-dynamic/src/main/c/sslcontext.c, openssl-dynamic/src/main/c/sslutils.c, openssl-dynamic/src/main/java/io/netty/internal/tcnative/NativeStaticallyReferencedJniMethods.java, openssl-dynamic/src/main/java/io/netty/internal/tcnative/SSL.java, openssl-dynamic/src/main/java/io/netty/internal/tcnative/SSLContext.java, pom.xml
Motivation:
OpenSSL 1.1.1 was released which supports TLSv1.3 and it is the now the current LTS release. We should be able to compile against it and also support TLSv1.3.
Modifications:
- Add some new native methods to allow to set TLSv1.3 ciphersuites
- Depending on if TLSv1.3 is supported or not set some flags
Result:
Be able to compile against OpenSSL 1.1.1 and make use of TLSv1.3. Fixes https://github.com/netty/netty-tcnative/issues/345 and https://github.com/netty/netty-tcnative/issues/256
=> Add support for TLSv1.3 when compiled against openssl 1.1.1

openssl-dynamic/src/main/c/ssl_private.h
Motivation:
We need to use 0 for SSL_OP_NO_TLSv1_3 when TLSv1.3 is not supported to not disable any protocols by mistake when its not supported at all.
Modifications:
Define SSL_OP_NO_TLSv1_3 as 0 when TLSv1.3 is not supported.
Result:
Correctly handle the case when TLSv1.3 is not supported and so be able to use it in this case.
=> Return 0 for SSL_OP_NO_TLSv1_3 when TLSv1.3 is not supported.

boringssl-static/pom.xml, libressl-static/pom.xml, openssl-static/pom.xml, pom.xml
Motivation:
We should use the correct phases for the native build. Which means we should ownload download and unpack the needed resources during generate-sources but do the compilation during the compile phase.
Modifications:
Break up tasks to execute in the correct phase.
Result:
Fixes https://github.com/netty/netty-tcnative/issues/120.
=> Use correct maven lifecycle phases during static builds.

pom.xml
Motivation:
We should be able to compile on recent versions of Java.
Modifications:
Add profiles and configuration to be able to build on Java8,9,10,11,12
Result:
Be able to build on recent versions of java
=> Adjust pom.xml to be able to compile on Java8,9,10,11,12

openssl-dynamic/src/main/c/sslcontext.c
Motivation:
We must not return early in certificate_cb if keytypes could not be detected as we correctly handle this case in the Java code. This is especially important to correctly support TLSv1.3
Modifications:
Do not return early when the keytypes could not be detected and just let the java callback handle it.
Result:
Be able to use TLSv1.3 correctly.
=> Do not return early in certificate_cb if keytypes could not be detected.

boringssl-static/pom.xml, libressl-static/pom.xml, openssl-static/pom.xml
Motivation:
ef30a10dcb9b21eb14fa1dc0bfcc249c235c809e changed the build to use generated-sources but missed to ensure we also compile the java classes in the generated jars.
Modifications:
Correctly include into jar.
Result:
Jars contain native code and java code.
=> Ensure generated-sources/java is included in jar.

openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/c/ssl_private.h, openssl-dynamic/src/main/c/sslcontext.c
Motivation:
BoringSSL chromium-stable branch supports TLSv1.3 now so we should do as well when compile against it.
Modifications:
Add support for TLSv1.3 when using boringssl
Result:
Easier for people to use TLSv1.3 as they will get it with netty-tcnative-boringssl-static
=> Support TLSv1.3 with compiling against boringssl

openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/c/sslcontext.c
Motivation:
Some code can be removed and also we should ensure we handle empty ciphers consistent between BoringSSL and OpenSSL.
Modifications:
- Remove not needed called for min protocol version when using BoringSSL
- Return when an empty ciphers string is given as this will fail in BoringSSL while just return on OpenSSL.
Result:
Cleaner and more consistent code.
=> Cleanup BoringSSL TLSv1.3 support and consistent handle empty ciphers.

.gitignore
Motivation:
CLion is using cmake to configure the project correctly. We should ignore these as these are not needed for building itself.
Modifications:
Ingore cmake files.
Result:
More things for git to ignore
=> Ignore cmake related files.

openssl-dynamic/src/main/c/ssl.c
Motivation:
While BoringSSL does not support SSL_get_sig_algs(...) we can make use of SSL_get0_peer_verify_algorithms for our use case.
Modifications:
Use SSL_get0_peer_verify_algorithms when BoringSSL is used and so have a correct implemention there as well (which is needed for ExtendedSSLSession in java).
Result:
Be able to correctly implement ExtendedSSLSession.getPeerSupportedSignatureAlgorithms() when using BoringSSL.
=> Correctly implement SSL.getSigAlgs(...) for BoringSSL

pom.xml
Motivation:
We should use the latest OpenSSL version for our static build.
Modifications:
Upgrade to 1.1.1a
Result:
Use latest OpenSSL version.
=> Upgrade to OpenSSL 1.1.1a for static build.

pom.xml
Motivation:
We should use the latest recommendated LibreSSL release for our static build.
Modifications:
Upgrade to 2.8.2 and adjust comment to explain where the SHA256 signature can be retrieved.
Result:
Use latest LibreSSL version
=> Update to latest recommended stable LibreSSL release

boringssl-static/pom.xml, libressl-static/pom.xml, openssl-dynamic/pom.xml, openssl-static/pom.xml
Motivation:
When the library is used as a JPMS dependency or transitive dependency
("tcnative-boringssl-static" for example), JVM attempts to trasform it
into a module and fails because "static" is a reserved word.
Modifications:
The change adds "Automatic-Module-Name" to manifests of all jar files.
Result:
JVM will use the "Automatic-Module-Name" instead of deriving the
module name from the jar file name.
The declared module name can also be used as a dependency name
in JPMS module declaration.
=> Adding Automatic-Module-Name to all manifests.

docker/docker-compose.centos-6.18.yaml, docker/docker-compose.debian-7.18.yaml
Motivation:
We should build with the latest JDK8 release.
Modifications:
Update JDK version.
Result:
Use latest JDK8 release on CI.
=> Update to latest JDK8 release.

openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/java/io/netty/internal/tcnative/SSL.java
This change accompanies the broader pull-request introduced by 
https://github.com/netty/netty/pull/8653 to allow access to the SSL session master key for debugging purposes.
Accessing the master key is useful if you ever need to decrypt the TLS session for debugging purposes with tools such as Wireshark.
Access of the field from the SSL session struct is direct as the wrapper method was only introduced in 1.1.0+  https://www.openssl.org/docs/man1.1.0/ssl/SSL_SESSION_get_master_key.html
=> Introduce a new native method to access the master key

openssl-dynamic/src/main/c/sslcontext.c
Motivation:
As explained in the SSL_set_cert_cb manpage 0 should be used to signal back errors. At the moment we use -1 which should only be used to signal back that the operation should be retried later.
See https://www.openssl.org/docs/man1.0.2/man3/SSL_set_cert_cb.html.
At the moment -1 also works as we not correctly handle SSL_ERROR_WANT_X509_LOOKUP in nettys ReferenceCountedOpenSslEngine and just treat SSL_ERROR_WANT_X509_LOOKUP as error (which is not correct).
Modifications:
Use 0 to signal a handshake error.
Result:
Use correct return value for errors.
=> Use correct return value in certificate_cb for errors.

openssl-dynamic/src/main/c/jnilib.c, openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/c/ssl_private.h, openssl-dynamic/src/main/c/sslcontext.c, openssl-dynamic/src/main/c/sslutils.c, openssl-dynamic/src/main/java/io/netty/internal/tcnative/CertificateCallbackTask.java, openssl-dynamic/src/main/java/io/netty/internal/tcnative/SSL.java, openssl-dynamic/src/main/java/io/netty/internal/tcnative/SSLContext.java, openssl-dynamic/src/main/java/io/netty/internal/tcnative/SSLTask.java
Motiviation:
Sometimes selection of the certificate can take a long time as it may be stored on a remote system (for example). We should support to offload selection of the certificate to an other thread and be able to retry the SSL operation after it is done.
This will also allow us to support the SSLEngine abstraction of SSLEngine.getDelegatingTask() and SSLEngineResult.HandshakeStatus.NEED_TASK.
Modification:
- Introduce SSLContest.setUseTasks(...) which allows to enable / disable the usage of tasks to offload certificate selection to an other thread.
- Introduce SSL.getTask(...) which allows to retrieve the task that will do the certificate selection ( and also other tasks in the future )
Result:
Be able to execute long running tasks for certificate selection ( and also others in the …
=> Support to offload certificate selection to different thread.

openssl-dynamic/src/main/c/sslcontext.c
Motivation:
In 11120b2d81fdc7de4619c904fc73622f77824ac8 we introduced the notion of offload operations as tasks but failed to ensure we init all fields of tcn_ssl_task_t. This can lead to strange side-effects if the OPENSSL_malloc(...) implementation does not memset.
Modifications:
Correctly init consumed to JNI_FALSE.
Result:
Correctly init struct.
=> Correctly init all fields of struct after malloc it.

pom.xml
Motivation:
There were new version of OpenSSL and LibreSSL released.
Modifications:
Update versions for the static builds.
Result:
Use latest versions on static builds.
=> Update OpenSSL to 1.1.1b and LibreSSL to 2.8.3

docker/docker-compose.centos.yaml, docker/docker-compose.debian.yaml
Motivation:
001d915209fe85cc6716b781f2fe25b5498c36f2 introduced settings.xml to use to deploy snapshots via CI but missed to also define env variables that will be used by docker-compose.
Modifications:
Define env variables to use.
Result:
Deploy snapshots via CI works as expected.
=> Define env variables to use when use shell with docker-compose

openssl-dynamic/src/main/c/native_constants.c, openssl-dynamic/src/main/c/ssl_private.h, openssl-dynamic/src/main/c/sslcontext.c, openssl-dynamic/src/main/java/io/netty/internal/tcnative/CertificateVerifierTask.java, openssl-dynamic/src/main/java/io/netty/internal/tcnative/NativeStaticallyReferencedJniMethods.java, openssl-dynamic/src/main/java/io/netty/internal/tcnative/SSL.java
Motivation:
BoringSSL supports offloading certificate validation to a different thread. This is useful as it may need to do blocking operations and so may block the EventLoop.
Modification:
Add BoringSSL specific code which allows to offload certificate validation (just as we already have code for certificate selection).
Result:
Be able to offload certificate validation when using BoringSSL.
=> Allow to offload certificate validation when using BoringSSL

openssl-dynamic/src/main/c/sslcontext.c
Motivation:
Encountered lint error about unused method SSL_cert_verify.
Modification:
Selectively compile for SSL_cert_verify when boringssl is not used.
Result:
No more lint error.
=> Don't include SSL_cert_verify method (unused) if not using boringssl.

docker/docker-compose.centos-6.18.yaml, docker/docker-compose.debian-7.18.yaml
Motivation:
We should use non oracle builds on the CI as JDK8 is not supported anymore.
Modifications:
Use adoptjdk builds
Result:
Use non oracle JDK builds on the CI.
=> Use adoptjdk builds for the CI

.gitignore, docker/docker-sync-compose.centos-6.18.yaml, docker/docker-sync.centos-6.18.yaml
Motivation:
docker-sync.io helps to speed up docker FS access on macOS and so make builds there a lot faster. We should add some config to help users use it.
Modifications:
Add docker-sync configs for centos-6.18 which is what we use for releases.
Result:
Faster builds via docker and when using macOS possible.
=> Add docker-sync config to step up docker-usage on macOS. (#8948)

boringssl-static/pom.xml, openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/c/sslcontext.c, openssl-dynamic/src/main/native-package/configure.ac
Motivation:
We should compile with -Wunused so we ensure we correctly remove unused code.
Modifications:
- Add -Wunused
- Add ifdef statements to ensure we only include stuff that is actually needed.
Result:
Cleaner / smaller code.
=> Compile with -Wunused

openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/c/sslcontext.c
Motivation:
ERR_err_string may return an internal shared buffer and so is not thread safe. While our usage seems to be fine (as we always pass in a buffer by ourself we should better just use ERR_err_string_n which will never return a shared buffer.
Modifications:
Replace ERR_err_string with ERR_err_string_n
Result:
More correct usage of APIs to print errors in a lib that may be used by multiple threads.
=> Avoid using un-thread-safe static buffers when printing errors

docker/docker-compose.centos-6.18.yaml, docker/docker-compose.debian-7.18.yaml, docker/docker-sync-compose.centos-6.18.yaml
Motivation:
There was a new java8 release, we should use it.
Modifications:
Update to adopt@1.8.212-03
Result:
Use latest java8 version on the CI
=> Update to latest java8 release

openssl-dynamic/src/main/c/sslcontext.c
Motivation:
At the moment we will segfault when PrivateKeyMethod.* will return null. While these methods should never return null we should guard against this
Modifications:
Return a failure when null is returned.
Result:
No more segfault possible when methods return null.
=> Prevert segfault when PrivateKeyMethod.* returns null

pom.xml
Motivation:
A new openssl 1.1.1 version was released.
Modifications:
Upgrade to 1.1.1c
Result:
Use latest openssl version.
=> Upgrade to openssl 1.1.1c

libressl-static/pom.xml, pom.xml
Motivation:
Latest stable release of libressl is 2.9.3
Modifications:
Update to latest stable release of libressl
Result:
Use latest stable release
=> Update to libressl 2.9.3

openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/c/ssl_private.h, openssl-dynamic/src/main/c/sslutils.c
Motiviation:
We recently upgraded to use libressl 2.9.2 when building our static linked version against libressl. We should also ensure we enable / disable features based on this version.
Modifications:
Adjust ifdef for libressl 2.9.2
Result:
Use correct features for libressl 2.9.2
=> Adjust ifdef for libressl 2.9.2

boringssl-static/pom.xml, libressl-static/pom.xml, openssl-dynamic/pom.xml, openssl-static/pom.xml
openSUSE x86_64 (probably more) uses `lib64`, e.g. `/usr/lib64`, and `configure` picks this up and builds the native library in `native-build/target/lib64` where maven is not looking. Instead, explicitly specify `--libdir=${project.build.directory}/native-build/target/lib` during
configuration.
FYI: This is similar to https://github.com/fusesource/hawtjni/issues/28 and borrows its solution
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netty/netty-tcnative/470)
=> fix native-build/target/lib wanted but build in native-build/target/lib64

docker/docker-compose.centos-6.18.yaml, docker/docker-compose.debian-7.18.yaml
Motivation:
We should use latest jdk 1.8 release
Modifications:
Update to adopt@1.8.212-04
Result:
Use latest jdk 1.8 on ci
=> Update to adopt@1.8.212-04

docker/docker-compose.centos-6.18.yaml, docker/docker-compose.debian-7.18.yaml
Motivation:
We should use latest jdk 1.8 release
Modifications:
Update to adopt@1.8.222-10
Result:
Use latest jdk 1.8 on ci
=> Update to adopt@1.8.222-10

boringssl-static/pom.xml
Motivation:
Some distributions install ninja as ninja-build and some as ninja executable. We should be able to build in both cases.
Modifications:
Add tests for alternative name and if found use it
Result:
Fixes https://github.com/netty/netty-tcnative/issues/475.
=> Build should work with ninja installed as ninja or ninja-build

openssl-static/pom.xml
Motivation:
We should better use https during build to download openssl as ftp is often restricted in coporate enviroments
Modifications:
Switch to https
Result:
Be able to build without ftp access
=> Use https to download openssl during build

libressl-static/pom.xml
Motivation:
At the moment we use http to download libressl but it would be better to use https
Modifications:
Replace http with https
Result:
Download over a secure connection
=> Use https when downloading libressl source

pom.xml
Motivation:
The current os-maven-plugin (1.4.0) has problems parsing /etc/os-release files in some cases, e.g. with ID_LIKE="opensuse suse"
Modifications:
update os-maven-plugin to 1.6.2 to fix these
Result:
Fixed `os.detected.release.like` property for openSUSE and potentially others.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netty/netty-tcnative/482)
=> upgrade os-maven-plugin to 1.6.2

docker/docker-compose.centos.yaml, docker/docker-compose.debian.yaml
Motivation:
As we use the docker files for the CI we should use the delegated mount option to speed up builds.
See https://docs.docker.com/docker-for-mac/osxfs-caching/#delegated
Modifications:
Use delegated mount option
Result:
Faster builds when using docker
=> Use delegated docker mount option to speedup builds

openssl-dynamic/src/main/c/jnilib.c, openssl-dynamic/src/main/c/sslcontext.c
Motivation:
malloc(...) may return NULL when there is not enough memory left. We need to handle this cases.
Modifications:
Add missing == NULL checks when using malloc
Result:
Fixes https://github.com/netty/netty-tcnative/issues/40
=> Always correctly handle the case when malloc(...) returns NULL

openssl-dynamic/src/main/c/jnilib.c, openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/c/sslcontext.c
Motivation:
Most of the New* functions may return NULL if no memory was left to fullfill the operation. We need to guard against this. Beside this we also need to guard against the case when we can not obtain a JNIEnv* reference for the calling thread.
Modifications:
- Add multiple NULL guards
- Ensure we could obtain a JNIEnv* reference and if not fail gracefully
- Guard against the case when the previously stored context was already cleared and we try to access it in an async callback.
Result:
Less possibilities for crashes
=> Guard against OOME errors in native code

pom.xml
https://www.openssl.org/news/openssl-1.1.1-notes.html
Motivation
Staying current with OpenSSL project.
Modifications
Updating patch version and SHA256 to latest OpenSSL release.
Result
Statically compiled version of TCN will use latest OpenSSL release.
=> OpenSSL 1.1.1d

openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/c/ssl_private.h, openssl-dynamic/src/main/c/sslcontext.c
Motivation:
We should share the code that is used to free / destory tcn_ssl_task instances to reduce the risk of bugs
Modifications:
Re-use code and so remove duplicates
Result:
Less error-prone code
=> Share code to free / release tcn_ssl_task* instances

boringssl-static/pom.xml
Motivation:
We need to ignore a specific warning when compiling on windows to be able to build boringssl.
Modifications:
Add /wd4091 as compiler flag on windows.
Result:
Be able to build boringssl and so boringssl-static on windows
=> Ignore one warning when compiling boringssl on windows

docker/Dockerfile.debian
Motivation:
Packages for debian 7 are now served via archive.debian.org so we need to adjust the docker file to be able to build the image
Modifications:
- Explicitly use archive.debian.org
- Pin versions where needed
Result:
Be able to build debian 7 docker image again
=> Fix dockerfile for debian 7

openssl-dynamic/src/main/c/sslcontext.c
Motivation:
Due a bug we did not correctly assing NULL to the pointer in freeDynamicTypeName
Modifications:
Correct dereference via * before assigning to NULL
Result:
Correctly assign NULL value
=> Correctly assign pointer to NULL in freeDynamicTypeName

openssl-dynamic/src/main/c/jnilib.c, openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/c/sslcontext.c, openssl-dynamic/src/main/c/sslutils.c
Motivation:
It's considered a good practice to init pointers to NULL when declared to have a defined value when accessing these.
Modifications:
Init pointers to NULL when declaring
Result:
Safer and cleaner code
=> Init pointers to NULL when declared

docker/docker-compose.centos-6.18.yaml, docker/docker-compose.debian-7.18.yaml
Motivation:
We should use latest jdk8 release to build on CI
Modifications:
Update to latest adoptjdk release
Result:
Use latest jdk8
=> Update to latest jdk8 release

pom.xml
Motivation:
We should allow to release from any centos version as long as its 6.x.
Modifications:
Not check the minor version but just the major version
Result:
Be able to release from any centos 6 version
=> Allow to release from any centos 6 version

pom.xml
Motivation:
Libressl 3.0.2 is out, we should build against it for the static libressl build
Modifications:
Update libressl version
Result:
Use latest libressl version for static libressl build
=> Update to libressl 3.0.2 for static libressl build

openssl-dynamic/src/main/c/bb.c, openssl-dynamic/src/main/c/jnilib.c, openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/c/sslcontext.c, openssl-dynamic/src/main/c/tcn.h
Motivation:
Usage of UNREFERENCED* macros is not really needed.
Modifications:
Remove usage of UNREFERENCED* macros to make code style more consistent
Result:
Fixes https://github.com/netty/netty-tcnative/issues/102.
=> Remove UNREFERENCED* macros and usage

.mvn/wrapper/maven-wrapper.properties
Motivation:
Latest recommended maven version is 3.6.2 so we should use it
Modifications:
Update from 3.5.2 to 3.6.2
Result:
Use latest recommended maven version
=> Update to latest recommended maven version

docker/Dockerfile.arch, docker/Dockerfile.opensuse, docker/README.md, docker/docker-compose.arch-18.yaml, docker/docker-compose.arch.yaml, docker/docker-compose.opensuse-151.18.yaml, docker/docker-compose.opensuse.yaml
As discussed in #471, this adds two more classifiers for the native libs: `suse` and `arch` to make the dynamically-linked libraries work on these systems as well.
changes:
- fixed linux release parsing by upgrading os-maven-plugin to 1.6.2 (see #482)
- add classifiers for suse and arch distributions
- add docker build files using
- openSUSE Leap 15.1
- Arch Linux
I'm not sure whether this covers all parts of the release pipeline (I tried to do the same that is done for Fedora already). I didn't see these docker images being used inside scripts in the repo though and I guess, you need to adapt some more settings to include the new artifacts into a release, don't you, @normanmaurer ?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> add suse and arch classifiers for native libraries

.mvn/wrapper/maven-wrapper.properties
Motivation:
Apache Maven 3.6.3 was released
Modifications:
Update to latest version
Result:
Use latest version to build
=> Use latest maven release

docker/docker-compose.centos-6.18.yaml, docker/docker-compose.debian-7.18.yaml
Motivation:
A new java 8 version was released, lets use it
Modifications:
Update to java8-242
Result:
Use latest java8 version
=> Update to java8-242

pom.xml
Motivation:
A new netty-build release is out.
Modifications:
Update to version 26
Result:
Use latest version of netty-build
=> Update to latest netty-build release

NOTICE.txt, license/LICENSE.aix-netbsd.txt, openssl-dynamic/src/main/c/jnilib.c
This fix is all about fixing the missing Dl_info & dladdr in AIX as mentioned in the issue #436 .
The code is taken from netbsd ( referenced in the issue #436 ).
=> Fix missing Dl_info & dladdr in AIX

docker/Dockerfile.centos, pom.xml
Motivation:
To be able to use the maven scm plugin with a specific revision of a repository we need to have git 2.x installed.
Modifications:
- Ensure we install git 2.x when on centos 6 (as it ships with 1.7)
- Update scm plugin
Result:
Be able to checkout specific revision with scm plugin
=> Use git 2.x on centos6 and update maven scm plugin

boringssl-static/pom.xml
Motivation:
Some tests do not compile on centos6 after the latest update of the chromium-stable branch. To workaround this we just dont compile the tests anymore for boringssl (we didnt run these anyway).
Modifications:
Explicit specify targets when building boringssl
Result:
Be able to build boringssl-static again on cents 6
=> Explicit specify build target for boringssl

boringssl-static/pom.xml
Motivation:
371ec47f4bde69aa008677081625280f41c042db did add an explicit build target. This is only needed on linux and even dont work at all on windows.
Modifications:
Only use explicit build target when on linux
Result:
Compiles again on windows
=> Only specify build target on linux

openssl-dynamic/src/main/c/ssl.c
Motivation:
We failed to free tcn_ssl_state_t via OPENSSL_free(...) which produced a small memory leak. This regression was introduced by https://github.com/netty/netty-tcnative/pull/498.
Modifications:
Correctly call OPENSSL_free(...) on previous allocated tcn_ssl_state_t.
Result:
Fixes https://github.com/netty/netty-tcnative/issues/532.
=> Correctly free tcn_ssl_state_t to prevent memory leak

boringssl-static/pom.xml
Motivation:
We should allow to compile netty-tcnative-boringssl-static with ASAN enabled which can be helpful to debug native leaks
Modifications:
Add new profile to allow building with ASAN
Result:
Be able to debug native leaks
=> Allow to build netty-tcnative-boringssl-static with ASAN enabled

pom.xml
Motivation:
There was a new release of openssl 1.1.1
Modifications:
Update to latest release for openssl-static
Result:
Use latest openssl version
=> Update to openssl 1.1.1e for openssl-static

openssl-static/pom.xml
Motivation:
Old openssl releases are hosted in a different location as new releases.
Modifications:
If we can not find the tarball in the expected location try to download from the location that contains old releases
Result:
https://github.com/netty/netty-tcnative/issues/536
=> Support building openssl-static with older openssl releases as well

pom.xml
Motivation:
A new openssl version was released with a security fix.
Modifications:
Update to 1.1.1g
Result:
Use latest version for static linking openssl
=> Update to openssl 1.1.1g

boringssl-static/pom.xml, docker/Dockerfile.cross_compile_aarch64, docker/README.md, docker/docker-compose.centos.yaml, openssl-dynamic/pom.xml
Motivation:
openssl-dynamic and boringssl-static which are packaged in Maven Repo don't support aarch64 platform.
Modifications:
Add cross compile support for openssl-dynamic and boringssl-static. Now their linux aarch64 packages can be released from the X86 machine.
**Note**:  when testing this PR locally, don't forget to fetch it in Dockerfile or fetch the PR in docker volume. 
```
RUN set -x && \
pushd netty-tcnative && \
git config --global user.email "you@example.com" && \
git config --global user.name "Your Name" && \
git fetch origin refs/pull/517/head:pr_517 && \
git checkout pr_517 && \
git rebase master && \
popd
```
Result:
Fixes #515
=> aarch64 cross compile support

pom.xml
Motivation:
Libressl 3.1.1 is the latest stable release which also supports TLS1.3 etc
Modifications:
Update libressl version
Result:
Use latest libressl version when compiling statically against libressl
=> Update to latest stable libressl release

boringssl-static/pom.xml
Fixup classifier specification in boringssl-static/pom.xml to correct a typo that was also seen in recent release of netty.
=> Fixup classifier in boringssl/pom.xml from aarch_64 to aarch64

openssl-dynamic/src/main/native-package/vs2010.vcxproj, vs2010.vcxproj.static.template
Motivation:
5d39363563bd8aa8ce3b6c2e7ee4155bd126e305 added a new c file but missed to include it in the build configuration for windows
Modifications:
Add sslsession.c to build configuration
Result:
Be able to build on windows again
=> Correctly include sslsession.c when building on windows

openssl-dynamic/src/main/c/sslsession.c
Motivation:
SSL_SESSION_up_ref was only added to openssl >= 1.1.0 before this we have to manually increment the reference count.
Modifications:
Manually increment reference count when an old version of openssl is used
Result:
Be able to compile against openssl < 1.1.0
=> Only use SSL_SESSION_up_ref when supported by used openssl version

openssl-dynamic/src/main/c/ssl_private.h, openssl-dynamic/src/main/c/sslcontext.c, openssl-dynamic/src/main/java/io/netty/internal/tcnative/SSL.java, openssl-dynamic/src/main/java/io/netty/internal/tcnative/SSLContext.java
Motivation:
Sometimes its useful to be able to adjust the number of used tickets for TLSv1.3. OpenSSL exposes some API for it.
Modifications:
Expose SSL_CTX_set_num_tickets via SSLContext
Result:
Be able to control te number of tickets to send when using TLSv1.3
=> Add support for SSL_CTX_set_num_tickets

boringssl-static/pom.xml, libressl-static/pom.xml, openssl-dynamic/pom.xml, openssl-dynamic/src/test/java/io/netty/internal/tcnative/AbstractNativeTest.java, openssl-static/pom.xml, pom.xml
Motivation:
We should better include the os / arch / classifier informations in the native library name. This way it is possible to have more then one on the classpath without any problems.
Modifications:
Adjust build scripts to include extra informations in the library name
Result:
Fixes https://github.com/netty/netty-tcnative/issues/555
=> Include os / arch / classifier informations in native library name

NOTICE.txt, boringssl-static/pom.xml, license/LICENSE.boringssl.txt, license/LICENSE.tomcat-native.txt
Motivation:
We statically compile against BoringSSL when releasing artifacts, thus we need to include BoringSSL in the NOTICE file to be compliant with the license
Modifications:
Add entry for BoringSSL
Result:
Fixes https://github.com/netty/netty-tcnative/issues/543
=> Update NOTICE file to include reference to BoringSSL

boringssl-static/pom.xml
Motivation:
We need to specify '-Wno-error=shadow' on aarch to be able to compile boringssl
Modifications:
Add -Wno-error=shadow
Result:
Be able to cross-compile again
=> Fix compilation error on aarch64

boringssl-static/pom.xml
Motivation:
a76e8101fae9e7dadbf5c869fc14990cfa2a3117 added the license files etc for BoringSSL to ensure we do the right thing in terms of attribution. That said we missed to add the same build config for cross-compiling
Modifications:
Add configuration for copy license when cross-compiling
Result:
Correctly do attribution
=> Also add license files when cross-compile

boringssl-static/pom.xml
Motivation:
We should also include the license files in the uber-jar as it includes the static compiled libs
Modifications:
Copy over license / notice files
Result:
Correctly attribute
=> Add license files to uber jar

pom.xml
Motivation:
9cd9f45bd4941581705ace76c7713b0c1b84f640 introduced a regression which lead to wrong naming of the classifier
Modifications:
Fix naming
Result:
Correct classifier used for openssl-dynamic
=> Fix classifier naming bug

pom.xml
Motivation:
We used an outdated libressl version.
Modifications:
Update to LibreSSL 3.1.4
Result:
Use up-to-date libressl version
=> Update to LibreSSL 3.1.4

boringssl-static/pom.xml
Motivation:
We had a typo in the manifest for aarch64.
Modifications:
Fix typo
Result:
Fixes https://github.com/netty/netty-tcnative/issues/571
=> Fix manifest entry for aarch64

pom.xml
Motivation:
We should ensure we not introduce any compatibility issues during build
Modifications:
Use japicmp maven plugin to validate we not introduce issues
Result:
More validation
=> Detect source / binary compatibility issues during build

pom.xml
Motivation:
openssl 1.1.1h was released so we should use it for the static build
Modifications:
Update openssl version
Result:
Use latest openssl version for static build
=> Update to latest openssl version for static build

docker/docker-compose.centos-6.18.yaml, docker/docker-compose.debian-7.18.yaml, docker/docker-sync-compose.centos-6.18.yaml
Motivation:
We should use the latest patch releases when building via docker
Modifications:
Update all java versions to the latest patch release
Result:
Use latest releases
=> Update java patch versions

openssl-dynamic/src/main/c/jnilib.c
Motivation:
In some situations we could have end up calling some functions with NULL parameters which in this case could lead to undefined behavior. All of this would have happened during loading of the native lib.
Modifications:
Add NULL check as guards and return early
Result:
Fix some possible undefined behavior
=> Add NULL checks to fix possible undefined behavior

openssl-dynamic/src/main/c/jnilib.c
Motivation:
We did use the incorrect parameter name and so compilation on windows failed
Modifications:
Use correct name
Result:
Compilation on windows works again
=> Fix compile error on windows

boringssl-static/pom.xml, libressl-static/pom.xml, openssl-dynamic/pom.xml, openssl-dynamic/src/main/c/bb.c, openssl-dynamic/src/main/c/error.c, openssl-dynamic/src/main/c/jnilib.c, openssl-dynamic/src/main/c/native_constants.c, openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/c/ssl_private.h, openssl-dynamic/src/main/c/sslcontext.c, openssl-dynamic/src/main/c/sslsession.c, openssl-dynamic/src/main/c/tcn.h, openssl-dynamic/src/main/native-package/vs2010.vcxproj, openssl-static/pom.xml, pom.xml, vs2010.vcxproj.static.template
Motivation:
We had a lot of duplication in our jni code which was mostly due macros but also related to how we support shading. By using netty-jni-util we can share all the code between netty and netty-tcnative ( and possible other jni based netty projects in the future).
Modifications:
- Use netty-jni-util and re-use its macros / functions
- Remove duplicated code
- Adjust build files
Result:
Less code duplication for JNI
=> Use netty-jni-util and so remove a lot of duplication

pom.xml
Motivation:
To be able to support macos 11 we should upgrade to apr 1.7.0 and apply the same patch as brew does to be able to build on it.
Modifications:
- Upgrade to apr 1.7.0
- Apply patch file if we building on macOS
Result:
Use latest stable apr release and be able to build on macos11
=> Update apr to 1.7.0 and apply patch to workaround problems on macos 11

boringssl-static/pom.xml, docker/Dockerfile.cross_compile_aarch64, docker/README.md, docker/docker-compose.centos.yaml, openssl-dynamic/pom.xml, pom.xml
Motivation:
We should use aarch_64 in our classifier / jni libname on aarch64 as os.detected.arch uses the name. Being non consistent (especially across our different projects) already gave us a lot of trouble in the past.
Let's fix this once for all.
Beside this I also noticed that the MANIFEST file entries were not correctly generated for aarch64
Modifications:
- Use aarch_64
- Fix MANIFEST entries
- Make docker files consistent and update to latest git to be able to build boringssl
Result:
More consistent classifier usage on aarch64
=> Use aarch_64 in a consistent way

pom.xml
Motivation:
We need to use APR 1.6.5 on windows as 1.7.0 doesn't compile on the platforms we support
Modifications:
Use APR 1.6.5 on windows
Result:
Be able to compile on windows again
=> Use APR 1.6.5 on windows as 1.7.0 doesnt compile

boringssl-static/pom.xml
Motivation:
When we generate the uber jars we should skip any extra work that is only needed while compiling the native lib itself.
Modifications:
Set related properties to false and so skip the steps.
Result:
Don't do extra work that is not required during building the uber jars
=> Skip extra work when generating uber jars

boringssl-static/pom.xml, libressl-static/pom.xml, openssl-dynamic/pom.xml, openssl-static/pom.xml, pom.xml
Motivation:
netty-jni-util is now also hosted on maven central. Let's use it
Modifications:
Adjust plugins to just unpack netty-jni-util and use it
Result:
Be able to use what is in the maven cache for netty-jni-util
=> Use netty-jni-util via maven central

pom.xml
A new version of OpenSSL is out (1.1.1i) and we should upgrade to it.
=> Upgrade to OpenSSL 1.1.1i

.github/workflows/ci-deploy.yml, docker/docker-compose.centos-6.18.yaml, docker/docker-compose.centos-6.yaml, docker/docker-compose.centos-7.yaml, docker/docker-compose.debian-7.18.yaml, docker/docker-compose.debian.yaml
Motivation:
We need to take special care when deploying snapshots as we need to generate the jars in multiple steps
Modifications:
- Use the nexus staging pluging to stage jars locally in multiple steps
- Add extra job that will merge these staged jars and deploy these
Result:
Related to netty/netty#10887
=> Correctly deploy artifacts that are build on different archs

boringssl-static/pom.xml, pom.xml
Motivation:
We should hardcode the BoringSSL commit sha so we know when we need to rebuild our docker images.
Modifications:
Hard code the commit SHA and ensure we use it
Result:
GitHub workflows will automatically re-compile BoringSSL when needed
=> Hardcode BoringSSL commit sha to use

pom.xml
Motivation:
fix-#607
Modifications:
use processor=x86 when ${os.detected.arch} equals x86_32.
Result:
Be able to load dll correctly on Eclipse RCP windows 32-bit.
=> Fix manifest entry for windows 32-bit 

boringssl-static/pom.xml
Motivation:
We need to override the configuration as otherwise we may use something which is defined in the parent pom and is not valid for our use-case
Modifications:
Add override
Result:
Correct maven config
=> Override configuration of dependency plugin in the uber generation

openssl-dynamic/src/main/c/ssl_private.h, openssl-dynamic/src/main/c/sslcontext.c, openssl-dynamic/src/main/java/io/netty/internal/tcnative/SSLContext.java
Motivation:
We can just do the conversation to wireformat in the java layer which allows us to remove some c code...
Modifications:
Replace the c code with the java code
Result:
Less c code FTW.
=> Replace c code that translate to wireformat to java

docker/Dockerfile.debian
Motivation:
Compiling GCC takes forever so let's just use a precompiled version
Modifications:
Use precompiled version
Result:
Speedup builds when docker container needs to be re-created
=> Speed up container creation by using pre-compile gcc version

.github/workflows/ci-build.yml, .github/workflows/ci-deploy.yml, .github/workflows/ci-pr.yml
Motivation:
Let's use consistent naming for the workflow jobs
Modifications:
Make naming consistent
Result:
Consistent naming
=> Use consistent naming for jobs

pom.xml
Fixed a NULL pointer deref in the X509_issuer_and_serial_hash() function
https://www.openssl.org/news/vulnerabilities.html#CVE-2021-23841
Fixed an overflow in the EVP_CipherUpdate, EVP_EncryptUpdate and EVP_DecryptUpdate functions
https://www.openssl.org/news/vulnerabilities.html#CVE-2021-23840
=> OpenSSL 1.1.1j (CVE-2021-23841, CVE-2021-23840)

openssl-dynamic/src/main/c/jnilib.c, pom.xml
Motifivation:
netty-jni-util 0.0.2.Final is incompatible with static linking. Before
the netty-jni-util dependency was introduced netty-tcnative supported
static linking via TCN_BUILD_STATIC. netty-jni-util 0.0.3.Final adds
static linking compatibility.
Modifications:
Bump netty-jni-util to version 0.0.3.Final and update to its new API
which requires the caller to manage packagePrefix.
Result:
Using latest version of netty-jni-util and restored static linking
compatibility.
=> Use netty-jni-util 0.0.3.Final

boringssl-static/pom.xml, docker/Dockerfile.cross_compile_aarch64, docker/docker-compose.centos-7.yaml, openssl-dynamic/pom.xml
Motivation:
LSE (https://mysqlonarm.github.io/ARM-LSE-and-MySQL/) can have a huge performance difference. Let's ensure we use a compiler that can support it.
Modifications:
Update to gcc10 when cross-compiling as it supports LSE and enables it by default
Result:
More optimized builds for aarch64
=> Let's use gcc10 when cross-compiling for LSE support

docker/Dockerfile.centos6
Motivation:
The third-party repos did turn out to be quite unstable.
Modifications:
- Just use vault.centos.org
- Use devtoolset-7
Result:
Hopefully more stable builds
=> Only use vault.centos.org

docker/docker-compose.centos-7.yaml, pom.xml
Motivation:
OpenSSL versions between 1.1.1h and 1.1.1j are vulnerable to
[CVE-2021-3450][1] and all 1.1.1 versions are vulnerable to
[CVE-2021-3449][2].
More in the OpenSSL security advisory, [here][3].
Modifications:
Update openssl-static to use the latest released version of OpenSSL,
1.1.1k.
Bump the version of OpenSSL used in the CentOS Docker container.
Result:
Artifacts of openssl-static that are no longer vulnerable to
CVE-2021-3449 and CVE-2021-3450.
[1]: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3450
[2]: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3449
[3]: https://www.openssl.org/news/secadv/20210325.txt
Signed-off-by: Nick Travers <n.e.travers@gmail.com>
=> Bump OpenSSL version to 1.1.1k

pom.xml
Motivation:
We did not use the latest chromium-stable commit as sha.
Modifications:
Update to 0310f724e77400636db71ae57230cae30a240c64
Result:
Base our next release on the latest chromium-stable commit
=> Update BoringSSL commit SHA to latest chromium-stable commit

scripts/finish_release.sh
Motivation:
We need to ensure that the parent will be deployed as well during the release process
Modifications:
Add -am so the parent will be deployed as well
Result:
netty-tcnative-parent is correctly deployed during release
=> Ensure parent will be deployed as well

openssl-dynamic/src/main/c/sslcontext.c
Motivation:
We did miss to unload the certificateVerifierTask_class. While this is not a big problem we should still do ensure the class is not referenced anymore
Modifications:
Unload class
Result:
Ensure all native loaded classes are unload
=> Unload certificateVerifierTask_class

openssl-dynamic/src/main/c/sslsession.c
Motivation:
We did miss to add a return statement when an openssl version < 1.1.x was used.
Modifications:
Add missing return statement.
Result:
Correctly handle the reference count
=> Add missing return statement

openssl-dynamic/src/main/c/ssl_private.h, openssl-dynamic/src/main/c/sslsession.c
Motivation:
If we did compile on older versions of openssl we tried to adjust the reference count of the SSLSession by directly accessing the field in the struct and increment it. While this sounded like a perfect workaround it turns out that this can cause all kind of problems and so also segfaults in general. Depending on how the openssl library was compile on the system we will have different layout of the struct and so can't really depend on a specific layout.
Modifications:
- Use weak linking if possible to detect on runtime of the SSLSession_up_ref function is present when using OpenSSL
- If the function is not present just return JNI_FALSE as we couldn't increment the reference count and so the user need to handle it. Which in our use-case in netty means that we can't cache the …
=> Only try to increment reference count if function is present

openssl-dynamic/src/main/c/sslsession.c
Motivation:
We should use the weak linking test if we not use BoringSSL. This is a followup of b7522ff6f95fce61509d776dbbfdc57780c0e372
Modifications:
Check if BoringSSL is used
Result:
Compiles against BoringSSL on macos
=> Only use ifdef if we don't use BoringSSL

openssl-dynamic/src/main/c/bb.c, openssl-dynamic/src/main/c/error.c, openssl-dynamic/src/main/c/jnilib.c, openssl-dynamic/src/main/c/native_constants.c, openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/c/sslcontext.c, openssl-dynamic/src/main/c/sslsession.c, openssl-dynamic/src/main/java/io/netty/internal/tcnative/Library.java
Motivation:
It turns out it is quite easy to cause a classloader deadlock in more recent java updates if you cause classloading while you are in native code. Because of this we should just workaround this issue by pre-load all the classes that needs to be accessed in the OnLoad function.
See https://github.com/netty/netty/issues/11209
Modifications:
Preload all classes that would otherwise be loaded by native OnLoad functions.
Result:
No more deadlocks possible.
=> Preload classes so we can't see a classloader deadlock

boringssl-static/pom.xml
Motivation:
Sometimes users want to use their own custom fork of boringssl. At the moment for this a modification of pom.xml is needed.
Modifications:
Allow to override the repository url for boringssl via -D...
Result:
Be able to use a custom fork of boringssl more easily
=> Allow to override the repository url of boringssl

.github/workflows/ci-build.yml, .github/workflows/ci-deploy.yml, .github/workflows/ci-pr.yml, .github/workflows/ci-release.yml, .github/workflows/codeql-analysis.yml, docker/docker-compose.arch.yaml, docker/docker-compose.centos-6.yaml, docker/docker-compose.centos-7.yaml, docker/docker-compose.debian.yaml, docker/docker-compose.opensuse.yaml
Motivation:
We should try to cache the maven dependencies and so reduce the likelyness of build failures due connections failures
Modifications:
- Adjust workflows to use the cache
- Adjust docker / docker-compose config to use the cache
Result:
More stable build
=> Use m2 repositry cache

.github/scripts/release_rollback.ps1, .github/scripts/release_rollback.sh, .github/workflows/ci-build.yml, .github/workflows/ci-deploy.yml, .github/workflows/ci-pr.yml, .github/workflows/ci-release.yml, .github/workflows/codeql-analysis.yml, .mvn/settings.xml, docker/docker-compose.arch.yaml, docker/docker-compose.centos-6.yaml, docker/docker-compose.centos-7.yaml, docker/docker-compose.debian.yaml, docker/docker-compose.opensuse.yaml, pom.xml
Motivation:
Just use MAVEN_OPTS to setup all the timeouts etc for dependency downloads. This way we at least can be sure these are applied.
Modifications:
- Use MAVEN_OPTS
- Remove ci profile
- Remove unused settings.xml file
- Always use ./mvnw
Result:
Build stability improvements
=> Use MAVEN_OPTS to setup timeouts for dependency downloads (#280)

openssl-dynamic/src/main/c/sslcontext.c, openssl-dynamic/src/main/java/io/netty/internal/tcnative/AsyncSSLPrivateKeyMethod.java, openssl-dynamic/src/main/java/io/netty/internal/tcnative/AsyncSSLPrivateKeyMethodAdapter.java, openssl-dynamic/src/main/java/io/netty/internal/tcnative/AsyncTask.java, openssl-dynamic/src/main/java/io/netty/internal/tcnative/CertificateCallbackTask.java, openssl-dynamic/src/main/java/io/netty/internal/tcnative/CertificateVerifierTask.java, openssl-dynamic/src/main/java/io/netty/internal/tcnative/ResultCallback.java, openssl-dynamic/src/main/java/io/netty/internal/tcnative/SSL.java, openssl-dynamic/src/main/java/io/netty/internal/tcnative/SSLContext.java, openssl-dynamic/src/main/java/io/netty/internal/tcnative/SSLPrivateKeyMethodSignTask.java, openssl-dynamic/src/main/java/io/netty/internal/tcnative/SSLPrivateKeyMethodTask.java, openssl-dynamic/src/main/java/io/netty/internal/tcnative/SSLTask.java
Motivation:
Sometimes we may want to run tasks in a fully async fashion. For example if we need to do a network operation to full fill the task.
This commit only makes use of the real async support for key-signing but we could also do the same for other tasks.
Modifications:
- Add AsyncTask that allows to run a task in an async fashion and notify the callback once done.
- Add AsyncSSLPrivateKeyMethod that makes use of the AsyncTask and so allow for a fully async implementation for key signing.
Result:
More flexible
=> Introduce the ability to run key-signing in an fully async fashion.

openssl-dynamic/src/main/c/native_constants.c, openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/java/io/netty/internal/tcnative/NativeStaticallyReferencedJniMethods.java, openssl-dynamic/src/main/java/io/netty/internal/tcnative/SSL.java
Motivation:
renegiotion is not supported by BoringSSL by default but sometimes when using on the client-side you might want to support it for CLIENT-AUTH.
See also https://github.com/apple/swift-nio-ssl/pull/111
Modifications:
Add native / java code to be able to enable support
Result:
Part of https://github.com/netty/netty/issues/11529
=> Allow to set renegiotion mode when BoringSSL is used

openssl-dynamic/src/main/c/ssl_private.h, openssl-dynamic/src/main/c/sslcontext.c, openssl-dynamic/src/main/java/io/netty/internal/tcnative/SSLContext.java
Motivation:
Sometimes it is useful to restrict the curves that are used.
Modifications:
Expose SSL_CTX_set1_curves_list via JNI
Result:
Be able to configure the curves that are used for a context
=> Allow to set the curves used

boringssl-static/pom.xml, pom.xml, scripts/finish_release.sh
Motivation:
We should support m1 as more and more users are switching to it.
Modifications:
- Add profile for boringssl-static to cross compile for m1
- Adjust finish release script to also include m1
Result:
Mac M1 is supported
=> Add support for mac m1

boringssl-static/pom.xml
Motivation:
Using -DOPENSSL_C11_ATOMIC brings a big performance boost. We should use it
Modifications:
- Add -DOPENSSL_C11_ATOMIC when compiling BoringSSL for linux aarch64
Result:
Less locking overhead on linux aarch64
=> Use -DOPENSSL_C11_ATOMIC when cross-compile for linux aarch64

pom.xml
Motivation:
ef6dd68503eaefdad800a7b905a1ad21a7e1408f did break OSGI support as we did not correctly include the generated MANIFEST
Modifications:
Fix configuration of plugins to include the correct MANIFEST file which has all the entries for OSGI
Result:
Fixes https://github.com/netty/netty-tcnative/issues/657
=> Fix OSGI support

docker/Dockerfile.centos6, docker/Dockerfile.debian, docker/docker-compose.centos-6.18.yaml, docker/docker-compose.debian-7.18.yaml
Motivation:
jabba is not updated anymore, let's use sdkman for JDK installation
Modifications:
- Switch to sdkman
- Update to latest JDK8 release
Result:
Be able to use latest JDK version again
=> Use sdkman for JDK installation

pom.xml
Motivation:
We should use https to download dependencies.
Modifications:
Switch to https when downloading apr
Result:
Fixes https://github.com/netty/netty-tcnative/issues/667
=> Use https to download apr

docker/Dockerfile.centos6, docker/Dockerfile.debian
Motivation:
Trying to use wget to download cmake gives certificate errors. Using curl fixes it
Modifications:
Switch to curl to download cmake
Result:
Be able to build docker image again
=> Use curl to download cmake

boringssl-static/pom.xml, libressl-static/pom.xml, openssl-dynamic/pom.xml, openssl-static/pom.xml, pom.xml
Motivation:
At the moment we even include the Bundle-NativeCode in the MANIFEST for th jars without classifier. This result in OSGI errors when depend on these.
Modifications:
Only add the Bundle-NativeCode when we actual include a native lib in the jar
Result:
Be able to use jars without classifiers with OSGI
=> Only include Bundle-NativeCode in MANIFEST if native code is included

docker/Dockerfile.centos6, docker/Dockerfile.cross_compile_aarch64, docker/Dockerfile.debian
Motivation:
We use the github cache to caching, there is no need to cache in the docker image as well
Modifications:
Remove caching in docker image
Result:
Cleanup
=> Remove caching in docker image

pom.xml
The library missing license information in maven central triggers failures for those running `maven-license-plugin` to verify licenses.
=> Include license distribution in pom

openssl-dynamic/src/main/native-package/configure.ac
Motivation:
We need to use -Wno-deprecated-declarations on newer macOS versions as otherwise the build will fail
Modifications:
Add  -Wno-deprecated-declarations
Result:
Be able to build on latest macOs
=> Specify -Wno-deprecated-declarations when compiling

libressl-static/pom.xml, openssl-static/pom.xml
Motivation:
We need to skip the javacmp check for modules that are not released.
Modifications:
Define the property to true
Result:
No more build failures. See https://github.com/netty/netty-tcnative/issues/686
=> Skip japicmp check for non released modules

boringssl-static/pom.xml
Motivation:
We explicitly need to set the target when we cross compile as otherwise it might fail
Modifications:
- Explicit set the target
- Define properties in the same place
Result:
No problem when cross compile
=> Explicit define the target when cross compile

pom.xml
Motivation:
We should support to compile the project on more recent JDKs.
Modifications:
- Add profiles for JDKs
- Update javadoc plugin
- Update cmp plugin
Result:
Be able to compile on more recent JDKs
=> Add profiles to allow to compile on newer JDKs

boringssl-static/pom.xml, libressl-static/pom.xml, openssl-dynamic/pom.xml, openssl-static/pom.xml
Motivation:
We need to add a Fragment-Host entry to the manifest for the jars that contain the native libs so its possible to use these in OSGI.
Modifications:
Add Fragment-Host entry to manifest.
Result:
Fixes https://github.com/netty/netty-tcnative/issues/683
=> Added Fragment-Host declaration to bundles shipping native libs

boringssl-static/pom.xml
Motivation:
We shouldn't repackage the native libs for the uber profile but better depend on the artifacts and so let the build tool handle this.
Modifications:
Change uber and uber-snapshot profile to not repackage
Result:
Less likely to see conflicts due multiple versions of tcnative on the classpath
=> Don't repackage jar for uber profile

pom.xml
Motivation:
OpenSSL 1.1.m was released, lets upgrade
Modifications:
Update to latest patch release
Result:
Use latest release
=> OpenSSL 1.1.1m was released

pom.xml
Motivation:
There is a new patch release of libressl
Modifications:
Update to latest release
Result:
Compile against latest patch release
=> Update to latest patch release of libressl

boringssl-static/pom.xml
Motivation:
6fb5b01208671c007ad7f752e51ccc8b25dfca2f introduced a change which changed how we package things. Unfortunally we missed to correctly flatten the pom.xml and so we not depend on the correct native libs.
Modifications:
- Add flatten plugin to the uber-* profiles
Result:
Depend on the correct native libs when uber profiles are used
=> Correctly flatten netty-tcnative-boringssl pom.xml

boringssl-static/pom.xml, libressl-static/pom.xml, openssl-classes/pom.xml, openssl-dynamic/pom.xml, openssl-static/pom.xml, pom.xml
Motivation:
We need to ensure we use different module names for openssl-classes and the other jars that contains the native code. Otherwise it is impossible to load these.
Modifications:
- Use different module name for openssl-classes
- Use the same module name for all the jars that contains native bits.
Result:
Fixes https://github.com/netty/netty-tcnative/issues/708
=> Use different module names for openssl-classes and the other jars

.github/workflows/ci-build.yml, .github/workflows/ci-deploy.yml, .github/workflows/ci-pr.yml, .github/workflows/ci-release.yml, openssl-dynamic/src/main/native-package/vs2010.vcxproj, vs2010.vcxproj.static.template
Motivation:
windows-2016 was removed so we need to use the next lowest which is 2019
Modifications:
Use windows-2019
Result:
Builds on windows work again
=> Use windows-2019 in workflows

pom.xml
Motivation:
openssl did release a new security release
Modifications:
Update to 1.1.1n
Result:
Use latest security update
=> Update to latest openssl release

openssl-dynamic/src/main/c/sslutils.c, pom.xml
Motivation:
A new libressl release is out which fixes a security vuln.
Modifications:
Update to 3.4.3
Result:
Use non affected libressl version
=> Upgrade to libressl 3.4.3

openssl-dynamic/pom.xml
Motivation:
We should ensure we link against openssl 1.1 on macOS even if openssl 3.x is installed as well.
Modifications:
Add configure argument
Result:
Fixes https://github.com/netty/netty-tcnative/issues/719
=> Ensure we link against openssl 1.1 on macOS

openssl-dynamic/src/main/c/jnilib.c, pom.xml
Improves musl compatibility and slightly improves efficiency.
Requires https://github.com/netty/netty-jni-util/pull/8.
=> Don't call strdup on packagePrefix.

boringssl-static/pom.xml, libressl-static/pom.xml, openssl-dynamic/pom.xml, openssl-static/pom.xml, pom.xml
Motivation:
The '-' is not allowed in module names and so the used module names are invalid.
See https://sormuras.github.io/blog/2018-11-16-invalid-automatic-module-names.html.
Modifications:
Adjust module names to not use invalid chars
Result:
Fixes https://github.com/netty/netty-tcnative/issues/724
=> Fix Automatic-Module-Name for jars that contain native libs

openssl-classes/src/main/java/io/netty/internal/tcnative/SSL.java, openssl-dynamic/src/main/c/ssl.c
I've been working on extending the pixie platform to support out of the box instrumentation for [twitter/finagle](https://github.com/twitter/finagle) and eventually the netty project (https://github.com/pixie-io/pixie/issues/407).
For those that aren't familiar, [Pixie](https://github.com/pixie-io/pixie) is an open source, Kubernetes Observability tool that provides auto instrumentation by leveraging eBPF. It has support for tracing network traffic for a variety of protocols (http/2, kafka, mysql, mux, etc) even if encrypted with openssl. Its openssl tracing support works by instrumenting the `SSL_read` and `SSL_write` functions through a uprobe. This uprobe captures the data just before encryption or just after decryption, in addition to navigating [openssl's rbio …
=> Add SSL.bioSetFd method to JNI code to support Pixie integration

pom.xml
Motivation:
OSGi does not recognize `aarch_64` (with the underscore) as a processor name.
Modification:
Add another rule to rewrite that processor name to not have the underscore for OSGi.
Result:
Our tcnative bundles should work again, on aarch_64 systems.
This is the tcnative equivalent of https://github.com/netty/netty/pull/12498
=> Fix aarch64 processor name for OSGi

pom.xml
Motivation:
A new openssl release was announced, lets use it
Modifications:
Update to 1.1.1q
Result:
Use latest release during build
=> Update to openssl 1.1.1q

boringssl-static/pom.xml, scripts/finish_release.sh
Motivation:
As m1/m2 becomes more used we should also have a profile to cross compile for intel.
Modifications:
- Add profile to cross-compile for intel when running on m1/m2.
- Adjust finish_release.sh script to use correct cross-compile profile based on the architecture.
Result:
Be able to cross compile for intel and also running the release on m1/m2
=> Add profile to cross compile for intel on macOs

boringssl-static/pom.xml
With the current maven configuration, when compiling from apple-silicon to intel produces arch64 binaries instead of x86_64 (via profile `mac-intel-cross-compile`)
```
❯ file libnetty_tcnative.jnilib
libnetty_tcnative.jnilib: Mach-O 64-bit dynamically linked shared library arm64
```
This PR replaces the wrong parameters in the compilation which now produces the correct target binaries
```
❯ file libnetty_tcnative.jnilib
libnetty_tcnative.jnilib: Mach-O 64-bit dynamically linked shared library x86_64
```
=> Fix BoringSSL osx cross-compilation incorrect binary output

openssl-classes/src/main/java/io/netty/internal/tcnative/NativeStaticallyReferencedJniMethods.java, openssl-classes/src/main/java/io/netty/internal/tcnative/SSL.java, openssl-dynamic/src/main/c/native_constants.c
Motivation:
We need to expose SSL3_RT_MAX_ENCRYPTED_LENGTH so we can use it to detemine the capacity of src ByteBuffer for unwrap operations.
Modifications:
Add method and constant that exposed SSL3_RT_MAX_ENCRYPTED_LENGTH
Result:
Be able to correctly size the capacity of the ByteBuffer
=> Expose SSL3_RT_MAX_ENCRYPTED_LENGTH via constant

openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/c/ssl_private.h, openssl-dynamic/src/main/c/sslcontext.c
(I wasn't able to figure out the build, but I'm hoping CI will catch if I messed anything up.)
Motivation:
Current revisions of BoringSSL have upgraded the `unsigned` parameter to a `size_t` one. (Folks requested that we start to work through -Wshorten-64-to-32 warnings.) This is broadly API-compatible but breaks netty-tcnative's weak symbol machinery because it copies the functionp prototype.
Modification:
Move the remaining functions BoringSSL always has into the OPENSSL_IS_BORINGSSL block and disable the weak symbol checks.
Result:
netty-tcnative builds with BoringSSL.
Further work can probably be done here to clean this up, depending on what the project wants. First of all, it's 2022 and you can probably just stop supporting OpenSSL 1.0.1. Then much of this goes away anyway.
Beyond …
=> Remove weak symbol when building with BoringSSL

.github/workflows/codeql-analysis.yml, docker/Dockerfile.centos6, docker/Dockerfile.cross_compile_aarch64, docker/Dockerfile.debian, docker/Dockerfile.opensuse, patches/apr_crypt.patch, pom.xml
Motivation:
We dont use any APR features that uses libcrypt so we can safely not link against it. This resolves various issues as some distributions otherwise need the extra installation of libxcrypt-compat etc.
Modifications:
- Add patchfile for APR configure.in to remove linking against libcrypt
- Patch APR during build
Result:
Fixes https://github.com/netty/netty-tcnative/issues/703
=> Patch APR to remove crypt dependency

boringssl-static/pom.xml, libressl-static/pom.xml, openssl-dynamic/pom.xml, openssl-static/pom.xml, pom.xml
Motivation:
The version of hawtjni that we are using is very old. Let's upgrade
Modifications:
Upgrade to 1.18
Result:
Use latest version of the plugin
=> Upgrade hawtjni plugin to latest version

openssl-dynamic/pom.xml
Motivation:
So junit dependencies are not transitively included when users depend on netty-tcnative in compile scope.
Modification:
Removed the junit dependencies from the openssl-dynamic submodule, so that they are inherited from netty-tcnative-parent with the proper test scope.
netty-tcnative-parent declares the junit dependencies as test scope in its dependencies.  But the openssl-dynamic submodule was overriding the scope to be the default (compile) scope.
Result:
Junit dependencies are not transitively included when users depend on netty-tcnative in compile scope.
Fixes #761
=> Remove compile scope junit dependencies from openssl-dynamic submodule

pom.xml
Motivation:
There was a new push into the chromium-stable branch. We should ensure we use the latest sha to static link against
Modifications:
Update to 1ccef4908ce04adc6d246262846f3cd8a111fa44
Result:
Use latest code of boringssl chromium-stable
=> Update to latest boringssl sha in chromium-stable branch

pom.xml
Motivation:
os-maven-plugin 1.6.2 does not recognize LoongArch information, os-maven-plugin supports LoongArch since 1.7.1
Modification:
Update pom.xml
Result:
LoongArch cpu information can be correctly identified
=> Bump up os-maven-plugin to 1.7.1

.github/workflows/ci-build.yml, .github/workflows/ci-deploy.yml, .github/workflows/ci-pr.yml, .github/workflows/ci-release.yml, .github/workflows/codeql-analysis.yml
Motivation:
Actions such as `checkout`, `cache`, `download-artifact`, and `upload-artifact` have a major upgrade available which is v3. We should consider upgrading to them for extended functionalities and support.
Modification:
Upgraded all of those above-mentioned actions to v3.
Result:
Latest actions version
=> Update multiple actions to v3

.github/workflows/ci-build.yml, .github/workflows/ci-deploy.yml, .github/workflows/ci-pr.yml, .github/workflows/ci-release.yml
Motivation:
We should use the latest setup-java action
Modifications:
- Upgrade to v3
- Add distribution setting
Result:
Use latest action version
=> Upgrade setup-java action

openssl-dynamic/src/main/c/sslcontext.c
Motivation:
We somehow missed to correctly create the ticket_keys_new atomic which then later on could cause a segfault when we tried to delete this
Modifications:
Correctly create the atomic
Result:
No more segfaults
=> Fix segfault which was caused by not creating the ticket_keys_new atomic

openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/c/sslcontext.c, openssl-dynamic/src/main/c/tcn_atomic.cpp, openssl-dynamic/src/main/c/tcn_atomic.h, openssl-dynamic/src/main/c/tcn_lock.cpp, openssl-dynamic/src/main/c/tcn_lock.h, openssl-dynamic/src/main/c/tcn_lock_rw.cpp, openssl-dynamic/src/main/c/tcn_lock_rw.h
Motivation:
8740651154d184c1dc90b9345e765edb42121119 did introduce a change to not use APR at all. This change did introduce a bug that could cause memory corruption / segfaults by passing a pointer to a pointer while just a pointer was expected.
Modifications:
- Correctly pass pointer
- Adjust c function to be more consistent and so always expect only a pointer
- Add extra NULL checks for safety reasons
Result:
No more segfaults
=> Fix possible corruption / segfault when using atomics

openssl-dynamic/pom.xml
Motivation:
https://github.com/netty/netty-tcnative/pull/725 fixed the Automatic-Module-Name for the static linked tcnative artifacts but missed to do the same for the dynamic linked one.
Modifications:
Define correct property
Result:
Be able to use dynamic linked tcnative with modules
=> Fix Automatic-Module-Name for dynamic linked tcnative

.github/workflows/ci-build.yml, .github/workflows/ci-deploy.yml, .github/workflows/ci-pr.yml, .github/workflows/ci-release.yml
Fixes #778
As per the linked issue, this workflow sets read-only top-level permissions on all workflows.
It is my understanding that the jobs in `release.yml` all require write permissions (they all set `git config`, so I assume commits will be written and pushed), so those have been given at the job level. This ensures that if a new job is added in the future that doesn't require write permissions, it'll only have read access.
If I misunderstood something and other workflows require additional permissions or some jobs in `release.yml` don't require write access, let me know and I'll fix the PR.
=> Set read-only permissions on GitHub workflows

openssl-classes/src/main/java/io/netty/internal/tcnative/SSLContext.java, openssl-dynamic/src/main/c/sslcontext.c
Motivation:
Sometimes its necessary to increase the maximum number of bytes a certificate chain can be
Modifications:
Expose SSL_CTX_set_max_cert_list
Result:
Be able to increase the limit
=> Expose SSL_CTX_set_max_cert_list

pom.xml
Motivation:
There is a new release
Modifications:
Upgrade to latest openssl release
Result:
Up to date openssl version
=> Upgrade to latest openssl 1.1.1 release

openssl-dynamic/src/main/c/sslcontext.c
Motivation:
During introducing https://github.com/netty/netty-tcnative/pull/759 I missed to add a free call which did introduce a small memory leak. This was not noticable for most users as creating and destroying of SSL context is usually very rare. That said some users might still do this and so notice the leak.
Modifications:
- Add missing free(...) call to match calloc(...)
- Move code of one function to the other as it was the only calling function. This simplifies the code and makes it less error-prone
Result:
Fixes https://github.com/netty/netty-tcnative/issues/788
=> Fix memory leak when creating and destroying a lot of context

docker/Dockerfile.centos6, pom.xml
Motivation:
We are using up-to-date sha.
Modifications:
Use sha ca1690e221677cea3fb946f324eb89d846ec53f2
Result:
Use latest commit of chromium-stable branch
=> Upgrade to latest sha in chromium-stable branch

boringssl-static/pom.xml
Adds -Wno-error=stringop-overflow flag to BoringSSL compilation so that it starts working again on specific OS/architecture configuration.
=> Fix compilation on some configurations

pom.xml
Motivation:
Upgrade to a newer, better supported version of openssl. I picked 3.0.8 as it's the latest version with FIPS support (which is better for my needs) but I'm happy to change to the bleeding edge version.
Modifications:
- Update to latest version
Result:
Use up-to-date version
I tested with my own application (using the openssl-static build), happy to run other tests. I did run `./mvnw test` and it passed on my machine.
=> upgrade openssl to 3.0.8

openssl-static/pom.xml
It looks like https://github.com/netty/netty-tcnative/commit/0828ffc73499269bbc6ffd8bf5ad3c98b0a67b9d broke the build on linux (my apologies!).
The openssl build now puts the libraries into `/lib64` instead of `/lib` so the following steps wouldn't include the native code in the jar. This change asks the build to put it into the old location (similar to the Mac build, which is what I tested in the last PR).
I tested this on a linux machine and verified that the build is now ~similarly sized to before the previous commit (and that it works)
=> Fix linux build for openssl-static

.github/workflows/ci-build.yml, .github/workflows/ci-deploy.yml, .github/workflows/ci-pr.yml, .github/workflows/ci-release.yml, .github/workflows/codeql-analysis.yml
Motivation:
When caching fails during workflow execution we should still continue the build as its just an optimization. Also we should use the new fork for docker layer caching
Modifications:
- Update action that does the docker layer caching to the new fork
- Ignore errors during caching
Result:
More stable builds
=> Update workflows to make things more robust when it comes to caching

.github/workflows/ci-build.yml, .github/workflows/ci-deploy.yml, .github/workflows/ci-pr.yml, .github/workflows/ci-release.yml
Motivation:
We need quite some diskspace due our ue of docker, let's ensure we have enough by free up what we dont need on the runner.
Modifications:
Use action that frees up diskspace
Result:
More stable build
=> Run action that frees up diskspace during workflows

openssl-dynamic/src/main/c/jnilib.c, openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/c/sslcontext.c, pom.xml
Motivation:
We should use weak references to hold global references to our own classes as otherwise it will be not possible to unload the classloader.
Modifications:
Use weak references for the classes in JNI.
Result:
No more classloader leaks. Related to https://github.com/netty/netty/issues/13480
=> Prevent classloader leak via JNI

boringssl-static/pom.xml, docker/Dockerfile.centos6
Motivation:
-DOPENSSL_C11_ATOMIC is not needed anymore for BoringSSL as it uses atomics by default now.
Modifications:
Remove -DOPENSSL_C11_ATOMIC
Result:
Cleanup
=> Remove obsolete flag when building BoringSSL

pom.xml
Motivation:
We dont need to patch APR anymore as the new version we are using is not suffering from the original problem
Modifications:
Remove build step that patches APR on macOS
Result:
Build works again on macOS
=> Remove build step that patches APR on macOS

boringssl-static/pom.xml
As discussed in [issue](https://github.com/netty/netty-tcnative/issues/799), considering the growing demand for FIPS compliance in security-sensitive environments, an official netty-tcnative release supporting FIPS validation would greatly benefit the open-source community. This would simplify integration and provide a reliable, community-supported solution.
Tools: cmake 3.20, ninja build 1.10.0, clang-12, golang, java 11, maven 3.6.3, libapr1, automake, autoconf, libtool, libunwind-dev, pkg-config
Fips validated BoringSSL commit used is 853ca1ea1168dff08011e5d42d94609cc0ca2e27
- Run Maven 
```
mvn clean install -f boringssl-static/pom.xml -Pfips-boringssl-static
```
- While build is running you should see in logs:
```
...
Boringssl is fips compliant
...
```
- After build steps are …
=> FIPS: Add pom profile to build fips compliant boringSSL netty-tcnative

boringssl-static/pom.xml
Motivation:
boringssl-static profile `mac-intel-cross-compile` incorrectly sets arch resulting in `osx-osx-x86_64` build classifier.
It also wrongfully sets the native lib name to `libnetty_tcnative_osx_osx_64`, making `netty-handler` unable to find it
If the intention of this profile was to build cross platform (from linux to mac), then `os.detected.name` can be overridden to still produce the similar result.
```xml
<os.detected.name>osx</os.detected.name>
```
Modifications:
Adjust arch to `x86_64` in maven profile for boringssl static
Result:
`./mvn -Pmac-intel-cross-compile -am -pl boringssl-static clean package` builds correctly on an apple silicon system
=> fix(boringssl): fix incorrect build profile for osx intel cross compile

pom.xml
Motivation:
Some tools depend on the Specification-* entries in the MANIFEST.MF. Unfortunaly
we don't add these at the moment
Modifications:
Configure plugin to also add the Specification-* entries
Result:
MANIFEST.MF contains Specification-* entries
=> Also add Specification-* entries to MANIFEST.MF

docker/Dockerfile.cross_compile_aarch64, docker/Dockerfile.debian
Motivation:
We need to run curl in insecure mode when install stuff via sdk as the version is too old
Modifications:
Add config that skips cert validation
Result:
Be able to build docker image
=> Fix docker image creation for debian

openssl-dynamic/src/main/c/sslcontext.c
Motivation:
33b2338ce415be8d3d7cb0a9aab962d2456af3ee introduced a bug which lead to return the incorrect value when no tasks are used.
Modifications:
Correctly return 1 when succesful
Result:
Correctly signal back that the cert could be selected
=> Return correct value from cert callback when no tasks are used

pom.xml
Motivation:
We are several released behind
Modifications:
Update openssl version
Result:
Use latest openssl version during build
=> Update to openssl 3.1.5

pom.xml
Motivation:
The chromium-stable branch of boringssl has new commits. We should pull them in.
Modifications:
Change commit sha of boringssl to the latest
Result:
Use latest code of chromium-stable branch
=> Update to latest boringssl chromium-stable commit

openssl-classes/src/main/java/io/netty/internal/tcnative/KeyLogCallback.java, openssl-classes/src/main/java/io/netty/internal/tcnative/SSLContext.java, openssl-dynamic/src/main/c/ssl_private.h, openssl-dynamic/src/main/c/sslcontext.c
Motivation:
Wireshark can decrypt TLS sessions during packet capture, if the session keys (etc.) are available from an SSL key log file. This log file format has become a de facto industry standard, and BoringSSL (and maybe the others too, didn't check) has a callback mechanism for delivering log lines in this format.
Modification:
Add `KeyLogCallback` interface and an `SSLContext.setKeyLogCallback` method, which integrators can easily implement the SSLKEYLOGFILE feature, or equivalent, on top of.
Result:
It is now possible to configure netty-tcnative in a way that TLS sessions can be decrypted at packet-capture time by Wireshark, making it easier to investigate and debug problems with TLS.
=> Add key log callback option to SSLContext

docker/Dockerfile.debian
Motivation:
Our curl version is too old, just don't verify while download sdkman
Modifications:
Download via -k
Result:
Build docker image again
=> Don't verify during download via curl

openssl-classes/src/main/java/io/netty/internal/tcnative/SSL.java, openssl-dynamic/src/main/c/ssl.c
Motivation:
As explained by @davidben this is not something that should be supported and it might break any time.
Modifications:
Make the method a no op and deprecate it
Result:
Fixes https://github.com/netty/netty-tcnative/issues/864
=> Deprecate bioSetFd and make it a no op

openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/c/ssl_private.h, openssl-dynamic/src/main/c/sslcontext.c, openssl-dynamic/src/main/c/sslutils.c, openssl-dynamic/src/main/native-package/m4/tcnative.m4
The `openssl-dynamic` module only compiles against OpenSSL 1.x.
The most significant change is that one no longer needs to provide DH parameters manually. By calling `SSL_CTX_set_dh_auto()`, OpenSSL will use the built-in parameters that match the key pair size. E.g. RSA 2048 will use DH 2048 and so on.
The property `jdk.tls.ephemeralDHKeySize`, which was used to affect the size of the DH parameters before, will be ignored when using the dynamically linked OpenSSL. Instead, the system OpenSSL library's config will be used.
Another change is how FIPS is managed because OpenSSL 3 introduces a "Provider" concept. The `FIPS_mode_set` is removed and is now replaced with `EVP_default_properties_enable_fips` which instructs OpenSSL to load the FIPS compliant provider, if no provider is explicitly …
=> Add OpenSSL 3.x support to openssl-dynamic

openssl-dynamic/src/main/c/cert_compress.c, openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/c/sslcontext.c
Motivation:
We didn't have all the necessary NULL checks in place which could cause a segfault when an operation failed in native code due an OOME (for example).
Modifications:
Add missing NULL checks
Result:
Correctly handle error scenarios
=> Add missing NULL checks

docker/Dockerfile.debian
Motivation:
We need to set the JAVA_VERSION before trying to use it, otherwise we might pick up the wrong version to install.
Modifications:
Ensure we set JAVA_VERSION first
Result:
SNAPSHOT deploys work again for debian
=> Set JAVA_VERSION before using it during installation of JDK via SDKMAN

boringssl-static/pom.xml, libressl-static/pom.xml, openssl-classes/src/main/java/module-info.yml, openssl-dynamic/pom.xml, openssl-static/pom.xml, pom.xml
tcnative should provide declarative modules for the set of its artifacts.
This is a preliminary contribution that will enable the support of declarative JPMS descriptors for Netty 4.2 branch.
Generated artifacts are multi release jar to remain compatible with Java 8.
This has been tested with `netty-tcnative-openssl-static` on my arm64 mac with a jlink generated image.
=> Declarative JPMS descriptors

boringssl-static/pom.xml, libressl-static/pom.xml, openssl-dynamic/pom.xml, openssl-static/pom.xml
Motivation:
We need to generate javadocs for all artifacts that we publish as otherwise the release process will fail
Modifications:
Generate empty javadocs jars when needed
Result:
Release process does not fail anymore
=> Ensure we generate javadocs for all artifacts

boringssl-static/pom.xml, docker/Dockerfile.centos6
Motivation:
We did not correctly specify the ASM flags to apply
Modifications:
- Use correct CMAKE flag for ASM
- Update to devtools-9
- Correctly specify boringssl targets to compile
Result:
Cleanup
=> Cleanup build for boringssl

boringssl-static/pom.xml
Motivation:
We should use the CMAKE specific flag when building
Modifications:
Replace /MT with MSVC_RUNTIME_LIBRARY=MultiThreaded
Result:
Cleanup of build
=> Replace /MT flag with MSVC_RUNTIME_LIBRARY=MultiThreaded when building for windows

boringssl-static/pom.xml
Motivation:
We did use the wrong jar name when cross compiling
Modifications:
Fix jar name
Result:
Cross compiling works again as expected
=> Fix jar name when cross compiling for macOs x86

boringssl-static/pom.xml
Motivation:
We need to use MACOSX_DEPLOYMENT_TARGET=10.13 when compiling BoringSSL as its the minimum as of today
Modifications:
Set MACOSX_DEPLOYMENT_TARGET=10.13
Result:
Be able to build on macOS
=> Use MACOSX_DEPLOYMENT_TARGET=10.13 when compiling BoringSSL

.gitignore, boringssl-static/pom.xml, boringssl-static/src/test/java/io/netty/internal/tcnative/NativeTest.java
Motivation:
We did end up with a BoringSSL artifact that could not load the native lib
Modifications:
-Add test that validates that the native lib can be loaded for BoringSSL
Result:
Correctly be able to use BoringSSL again
=> Fix BoringSSL artifact

boringssl-static/pom.xml, boringssl-static/src/test/java/io/netty/internal/tcnative/NativeTest.java
Motivation:
We need to ensure we only add the extra ldflags on linux as otherwise compilation will fail on macOS
Modifications:
Add the ldflags on linux only
Result:
Be able to compile on macOS again
=> Only add extra ldflags on linux

openssl-dynamic/src/main/c/sslcontext.c
Motivation:
BoringSSL changed the minimum TLS version to TLS1_2 by default. We should set it to TLS1 to be able to support older versions via netty.
Modifications:
Explicit set min TLS version
Result:
Supporting more TLS versions again
=> Explicit set minimum version to TLS1 when using BoringSSL

docker/Dockerfile.centos6
Motivation:
Let's just skip running the tests to speedup building the docker image
Modifications:
Don't run the test while building / installing perl
Result:
Faster to build docker image
=> Don't run testsuite when installing perl via perlbrew

docker/Dockerfile.arch, docker/Dockerfile.centos6, docker/Dockerfile.cross_compile_aarch64, docker/Dockerfile.debian, docker/Dockerfile.opensuse
Motivation:
We should explicit specify the platform we use for docker to ensure our build produce the correct artifacts
Modifications:
Add --platform=linux/amd64 to docker files
Result:
Ensure build produces correct artifacts
=> Explicit specify the platform for Docker files

boringssl-static/pom.xml, docker/Dockerfile.cross_compile_aarch64, docker/docker-compose.centos-7.yaml, pom.xml
Motivation:
Let's try to keep logic together to make it easier to keep track of changes
Modifications:
Move logic for cross compile to pom file.
Result:
Easier to maintain
=> Move logic for static cross-compile for linux-aarch64 to pom file

docker/Dockerfile.centos6
Motivation:
We need to force the installation of perlbrew otherwise the docker image generation might fail
Modifications:
Add --force
Result:
Docker image can be build again
=> Force installation of perlbrew

boringssl-static/pom.xml
Motivation:
This branch is already specified in the top-level project. However, when the stable branch is specified in the boringssl-static subproject, I get the stable branch when I build locally. Making the change in both places ensures there's no confusion in the build system.
Modification:
Change the `boringsslBranch` property to `master` in the boringssl-static subproject.
Result:
Local, CI, and all other builds always use the master-branch version of boringssl.
=> Use boringssl master in boringssl-static subproject

openssl-classes/src/main/java/io/netty/internal/tcnative/SSL.java, openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/c/ssl_private.h
Motivation:
At the moment its only possible to set the curves / groups per SSL_CTX instance. Sometimes we need to pick them based on the SSL instance.
Modifications:
Add methods to allow setting curves / groups
Result:
Be able to specify curves / groups per SSL instance
=> Add method to allow to set curves / groups per SSL instance

boringssl-static/pom.xml, pom.xml
Motivation:
BoringSSL does not have a master branch anymore, switch to main
Modifications:
Switch to main branch
Result:
Project builds again
=> Use main branch for BoringSSL

boringssl-static/pom.xml, openssl-dynamic/src/main/native-package/configure.ac, pom.xml
Motivation:
BoringSSL had an important fix that we want to consume https://boringssl.googlesource.com/boringssl/+/cccf8525db8a57153d3cb3e22efed2db4b71a8ab
Modifications:
Update to latest sha
Result:
Use latest boringssl code
=> Update to latest boringssl sha

openssl-dynamic/src/main/c/ssl.c
Always pass `false` as the second parameter to
`SSL_get_signature_algorithm_name()`. This forces BoringSSL to omit the curve name and return algorithm names in the style expected by callers of `SSL.getSigAlgs()`. Previously this parameter was only false for TLS 1.2.
This change does *not* have associated tests because I was unable to find any.
This is to fix #923
=> Fix SSL.getSigAlgs() on BoringSSL for TLS 1.3

.github/scripts/bundle_create.sh, .github/scripts/bundle_upload.sh, .github/scripts/local_staging_merge_release.sh, .github/scripts/local_staging_merge_snapshot.sh, .github/workflows/ci-deploy.yml, .github/workflows/ci-release.yml, boringssl-static/pom.xml, docker/docker-compose.centos-6.yaml, docker/docker-compose.centos-7.yaml, docker/docker-compose.debian.yaml, pom.xml
Motivation:
OSSRH is deprecated and will be shut down soon. Let's switch to using maven central
Modifications:
- Replace old plugin with central-publishing-maven-plugin for release
- Adjust workflow to setup the right token / password
- Add scripts
Result:
Snapshot deployments and release works again
=> Migrate using maven central

.github/workflows/ci-build.yml, .github/workflows/ci-deploy.yml, .github/workflows/ci-pr.yml, .github/workflows/ci-release.yml, .github/workflows/codeql-analysis.yml
Motivation:
We should cancel any running / queued job when a new change was pushed to the affected branch. This will ensure we not tie up resources.
Modifications:
Add new concurrency config to workflows
Result:
Cancel jobs that are not useful anymore
=> Cancel running / queue jobs when a new change was pushed to branch

.github/workflows/ci-build.yml, .github/workflows/ci-pr.yml, docker/Dockerfile.al2023, docker/docker-compose.al2023.yaml, openssl-classes/src/main/java/io/netty/internal/tcnative/NativeStaticallyReferencedJniMethods.java, openssl-classes/src/main/java/io/netty/internal/tcnative/SSL.java, openssl-classes/src/main/java/io/netty/internal/tcnative/SSLContext.java, openssl-dynamic/src/main/c/cert_compress.c, openssl-dynamic/src/main/c/cert_compress.h, openssl-dynamic/src/main/c/native_constants.c, openssl-dynamic/src/main/c/ssl.c, openssl-dynamic/src/main/c/ssl_private.h, openssl-dynamic/src/main/c/sslcontext.c, openssl-dynamic/src/main/c/sslsession.c, openssl-dynamic/src/main/c/sslutils.c
Hello,
I'm an engineer at AWS working on AWS-LC, AWS's open-source fork of Google's BoringSSL. We would like to propose adding AWS-LC support to netty-tcnative, alongside its existing support for OpenSSL, BoringSSL, and LibreSSL.
AWS-LC shares a similar API surface area to the existing BoringSSL integration within your library, while providing additional benefits for users.
We are committed to backwards compatibility and maintain extensive CI testing infrastructure that continuously validates compatibility with many open-source projects.
We plan to add netty-tcnative compatibility testing to this suite to ensure ongoing compatibility.
Some of the highlights offered by this integration:
1. Performance optimizations specifically targeted for modern CPU architectures, including AWS Graviton …
=> Support for building with AWS Libcrypto (AWS-LC)

pom.xml
Motivation:
Motivation:
It's been a while since we updated our used BoringSSL version.
Modifications:
Update to sha of current BoringSSL commit
Result:
Use latest BoringSSL version as of today
=> Update to latest BoringSSL commit sha

NOTICE.txt, license/LICENSE.boringssl.txt
Motivation:
The used version of BoringSSL is ASL2
Modifications:
Update and so fix license informations for BoringSSL
Result:
Include correct license for BoringSSL
=> Include correct license informations for BoringSSL

pom.xml
Motivation:
A new jni-util version was released which replaced some code which had no clear licensing.
Modifications:
Upgrade to latest version
Result:
Clear licensing of jni-util depndency
=> Update jni-util version to clarify licensing
